import { candidate, cocktail } from "../lib/candidate.mjs";
import { ing } from "../lib/ing.mjs";

/** @returns {import("../lib/candidate.mjs").candidate[]} */
export const items = [
  candidate({
    sourceTier: "high_quality_secondary",
    sourceTitle: "Smuggler's Cove",
    sourceAuthor: "Martin Cate & Rebecca Cate",
    sourceUrl: "",
    sourceRecipe: "Smuggler's Cove spec (Jamaican rum, allspice dram, lime)",
    recipeProvenance: "Modern tiki canon documenting Jamaican bar culture.",
    historicalNotes:
      "Named for the Lion's Tail tavern legend in Kingston; the allspice dram marks it as a Jamaican cousin to the sour template.",
    rarity: "hidden_gem",
    funFact:
      "Allspice dram turns a plain bourbon sour into something that smells like Kingston spice markets—one of the few classics built around pimento liqueur.",
    yearInvented: null,
    regionOfOrigin: "Jamaica",
    alternateNames: ["Lion's Tail"],
    cocktail: cocktail({
      name: "Lion's Tail",
      slug: "lion-tail",
      glass: "Coupe",
      family: "Sour",
      method: "Shaken",
      tags: ["classic", "historical"],
      ingredients: [
        ing("bourbon", "Bourbon", "spirit", 60),
        ing("allspice-dram", "Allspice dram", "liqueur", 15),
        ing("lime-juice", "Lime juice", "juice", 22.5),
        ing("simple-syrup", "Simple syrup", "syrup", 7.5),
        ing("angostura-bitters", "Angostura bitters", "bitters", 2, "dash"),
      ],
      garnish: ["Lime wheel"],
      preparation: [
        "Shake all ingredients with ice.",
        "Strain into a chilled coupe.",
        "Garnish with lime.",
      ],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "Smuggler's Cove",
    sourceAuthor: "Martin Cate & Rebecca Cate",
    sourceUrl: "",
    sourceRecipe: "Smuggler's Cove Corn 'n' Oil (blackstrap, falernum, lime)",
    recipeProvenance: "Barbados highball documented in modern tiki scholarship.",
    historicalNotes:
      "Barbados' everyday rum highball—falernum and blackstrap on ice predates the tiki movement but anchors Caribbean rum culture.",
    rarity: "well_known",
    funFact:
      "Barbados bartenders treat this like a beer: blackstrap rum, falernum, and a spent lime shell on ice—no shaker required.",
    yearInvented: null,
    regionOfOrigin: "Barbados",
    alternateNames: ["Corn 'n' Oil"],
    cocktail: cocktail({
      name: "Corn and Oil",
      slug: "corn-and-oil",
      glass: "Rocks",
      family: "Highball",
      method: "Built",
      tags: ["classic", "tiki"],
      ingredients: [
        ing("blackstrap-rum", "Blackstrap rum", "spirit", 60),
        ing("falernum", "Falernum", "liqueur", 15),
        ing("lime-juice", "Lime juice", "juice", 15),
      ],
      garnish: ["Spent lime shell"],
      preparation: [
        "Add rum and falernum to a rocks glass with ice.",
        "Squeeze lime and drop shell into the glass.",
        "Stir briefly and serve.",
      ],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Airmail (rum, lime, honey, champagne)",
    recipeProvenance: "1930 Savoy printing; champagne float highball.",
    historicalNotes:
      "Craddock's Airmail reads like a Daiquiri lengthened with bubbly—named for the romance of early aviation mail routes.",
    rarity: "classic",
    funFact:
      "Harry Craddock floated champagne on a honeyed rum sour and called it Airmail—1930s marketing for the dawn of transatlantic flight.",
    yearInvented: 1930,
    regionOfOrigin: "London, UK",
    alternateNames: [],
    cocktail: cocktail({
      name: "Airmail",
      slug: "airmail",
      glass: "Collins",
      family: "Highball",
      method: "Shaken",
      tags: ["classic", "historical", "champagne"],
      ingredients: [
        ing("rum-white", "White rum", "spirit", 45),
        ing("lime-juice", "Lime juice", "juice", 15),
        ing("honey-syrup", "Honey syrup", "syrup", 15),
        ing("champagne", "Champagne", "wine", 60),
      ],
      garnish: ["Lime wheel"],
      preparation: [
        "Shake rum, lime, and honey syrup with ice.",
        "Strain into a Collins glass over ice.",
        "Top with chilled champagne and garnish.",
      ],
    }),
  }),
  candidate({
    sourceTier: "high_quality_secondary",
    sourceTitle: "Beachbum Berry Remixed",
    sourceAuthor: "Jeff Berry",
    sourceUrl: "",
    sourceRecipe: "Berry-reconstructed Don the Beachcomber Taboo",
    recipeProvenance: "Tiki historian spec from lost Donn Beach notes.",
    historicalNotes:
      "Don the Beachcomber's lost-book recipe Berry calls Taboo—distinct from the later passion-fruit tiki slug already in CRAFT as taboo-tiki.",
    rarity: "deep_cut",
    funFact:
      "Jeff Berry dug this name out of Donn Beach's cryptic notebooks—a banana-and-coconut blend separate from the passion-fruit Taboo already in the expanded set.",
    yearInvented: 1937,
    regionOfOrigin: "Hollywood, USA",
    alternateNames: [],
    cocktail: cocktail({
      name: "Taboo",
      slug: "taboo",
      glass: "Tiki mug",
      family: "Tiki",
      method: "Blend",
      tags: ["tiki", "historical"],
      ingredients: [
        ing("rum-white", "White rum", "spirit", 45),
        ing("rum-dark", "Dark rum", "spirit", 22.5),
        ing("lime-juice", "Lime juice", "juice", 22.5),
        ing("banana-liqueur", "Banana liqueur", "liqueur", 15),
        ing("coconut-cream", "Coconut cream", "mixer", 30),
        ing("falernum", "Falernum", "liqueur", 7.5),
      ],
      garnish: ["Mint sprig", "nutmeg"],
      preparation: [
        "Blend all ingredients with crushed ice until smooth.",
        "Pour into a tiki mug.",
        "Garnish with mint and grated nutmeg.",
      ],
    }),
  }),
  candidate({
    sourceTier: "high_quality_secondary",
    sourceTitle: "Beachbum Berry Remixed",
    sourceAuthor: "Jeff Berry",
    sourceUrl: "",
    sourceRecipe: "Donn Beach Grog (1930s Beachcomber blend)",
    recipeProvenance: "Reconstructed from Don the Beachcomber recipe logs.",
    historicalNotes:
      "One of Donn Beach's early grogs served at the Hollywood Beachcomber—rum, citrus, and spice built for long afternoons.",
    rarity: "deep_cut",
    funFact:
      "Before the Zombie made Donn Beach famous, grogs like this one trained Hollywood regulars to expect rum served like a meal.",
    yearInvented: 1934,
    regionOfOrigin: "Hollywood, USA",
    creator: "Donn Beach",
    bar: "Don the Beachcomber",
    city: "Hollywood",
    creationYear: 1934,
    alternateNames: ["Don's Beach Grog"],
    cocktail: cocktail({
      name: "Donn Beach Grog",
      slug: "donn-beach-grog",
      glass: "Tiki mug",
      family: "Tiki",
      method: "Blend",
      tags: ["tiki", "historical"],
      ingredients: [
        ing("gold-rum", "Gold rum", "spirit", 45),
        ing("rum-dark", "Dark rum", "spirit", 22.5),
        ing("lime-juice", "Lime juice", "juice", 22.5),
        ing("grapefruit-juice", "Grapefruit juice", "juice", 22.5),
        ing("honey-syrup", "Honey syrup", "syrup", 15),
        ing("allspice-dram", "Allspice dram", "liqueur", 7.5),
        ing("club-soda", "Club soda", "mixer", 30),
      ],
      garnish: ["Mint sprig"],
      preparation: [
        "Blend rums, juices, honey, and pimento dram with crushed ice.",
        "Pour into a tiki mug and top with a splash of soda.",
        "Garnish with mint.",
      ],
    }),
  }),
  candidate({
    sourceTier: "high_quality_secondary",
    sourceTitle: "Death & Co",
    sourceAuthor: "David Kaplan, Nick Fauchald, Alex Day",
    sourceUrl: "",
    sourceRecipe: "Death & Co Eastern Standard (bourbon, mint, lime, sugar)",
    recipeProvenance: "Milk & Honey lineage modern classic.",
    historicalNotes:
      "A bourbon Southside—mint and lime soften the whiskey for a bar snack-friendly sipper born in New York's neo-speakeasy era.",
    rarity: "well_known",
    funFact:
      "Death & Co framed this as a bourbon Southside: mint bruised with lime and simple syrup so the whiskey reads bright, not boozy.",
    yearInvented: 2007,
    regionOfOrigin: "New York, USA",
    creator: "Phil Ward",
    bar: "Milk & Honey",
    city: "New York",
    creationYear: 2007,
    alternateNames: [],
    cocktail: cocktail({
      name: "Eastern Standard",
      slug: "eastern-standard",
      glass: "Coupe",
      family: "Sour",
      method: "Shaken",
      tags: ["modern-classic"],
      ingredients: [
        ing("bourbon", "Bourbon", "spirit", 60),
        ing("lime-juice", "Lime juice", "juice", 22.5),
        ing("simple-syrup", "Simple syrup", "syrup", 15),
        ing("mint-leaves", "Mint leaves", "garnish", 8, "leaves"),
      ],
      garnish: ["Mint sprig"],
      preparation: [
        "Gently muddle mint with syrup and lime in a shaker.",
        "Add bourbon and ice; shake well.",
        "Fine-strain into a chilled coupe and garnish with mint.",
      ],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Hotel Nacional Special (rum, pineapple, lime, apricot)",
    recipeProvenance: "1930s Cuban classic via Savoy printing.",
    historicalNotes:
      "Named for Havana's Hotel Nacional—pineapple and apricot liqueur wrap around Cuban rum in a pre-revolution luxury hotel template.",
    rarity: "classic",
    funFact:
      "Havana's Hotel Nacional lent its name to this pineapple-apricot rum sour long before American tourists discovered the mojito.",
    yearInvented: 1930,
    regionOfOrigin: "Havana, Cuba",
    alternateNames: ["Hotel Nacional Special"],
    cocktail: cocktail({
      name: "Hotel Nacional",
      slug: "hotel-nacional",
      glass: "Coupe",
      family: "Sour",
      method: "Shaken",
      tags: ["classic", "historical"],
      ingredients: [
        ing("rum-white", "White rum", "spirit", 45),
        ing("pineapple-juice", "Pineapple juice", "juice", 30),
        ing("lime-juice", "Lime juice", "juice", 15),
        ing("apricot-liqueur", "Apricot liqueur", "liqueur", 15),
      ],
      garnish: ["Pineapple wedge"],
      preparation: [
        "Shake all ingredients with ice.",
        "Strain into a chilled coupe.",
        "Garnish with pineapple.",
      ],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "Pimm's No. 1 Cup",
    sourceAuthor: "James Pimm",
    sourceUrl: "",
    sourceRecipe: "Classic Pimm's Cup (No. 1, lemon, cucumber, lemonade)",
    recipeProvenance: "British pub and tennis standard since mid-1800s.",
    historicalNotes:
      "James Pimm sold the tonic cup at his London oyster house; cucumber and effervescence made it the default English summer drink.",
    rarity: "well_known",
    funFact:
      "Wimbledon pours thousands of these each year—Pimm's No. 1 was originally marketed as a digestive tonic, not a lawn party prop.",
    yearInvented: 1840,
    regionOfOrigin: "London, UK",
    creator: "James Pimm",
    city: "London",
    creationYear: 1840,
    alternateNames: ["Pimm's No. 1 Cup"],
    cocktail: cocktail({
      name: "Pimm's Cup",
      slug: "pimm-cup",
      glass: "Collins",
      family: "Highball",
      method: "Built",
      tags: ["classic"],
      ingredients: [
        ing("pimm-s-no-1", "Pimm's No. 1", "liqueur", 60),
        ing("lemonade", "Lemonade", "mixer", 90),
        ing("lemon", "Lemon slice", "garnish", 1, "slice"),
        ing("cucumber", "Cucumber", "garnish", 2, "slice"),
      ],
      garnish: ["Cucumber ribbon", "mint sprig", "strawberries"],
      preparation: [
        "Fill a Collins glass with ice.",
        "Add Pimm's and top with chilled lemonade.",
        "Garnish with cucumber, fruit, and mint.",
      ],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "IBA Official Cocktails",
    sourceAuthor: "International Bartenders Association",
    sourceUrl: "https://iba-world.com/iba-cocktail/the-unforgettables/paradise/",
    sourceRecipe: "IBA Paradise (gin, apricot brandy, orange juice)",
    recipeProvenance: "IBA Unforgettables list.",
    historicalNotes:
      "A two-ingredient gin sling lengthened with orange—post-war IBA canon showcasing apricot brandy in a simple sour family drink.",
    rarity: "classic",
    funFact:
      "The IBA Paradise is barely a recipe—gin, apricot brandy, and orange juice—but that simplicity made it a hotel-bar staple across Europe.",
    yearInvented: 1930,
    regionOfOrigin: "France",
    alternateNames: [],
    cocktail: cocktail({
      name: "Paradise",
      slug: "paradise",
      glass: "Coupe",
      family: "Sour",
      method: "Shaken",
      tags: ["classic", "iba"],
      ingredients: [
        ing("gin", "Gin", "spirit", 30),
        ing("apricot-brandy", "Apricot brandy", "liqueur", 30),
        ing("orange-juice", "Orange juice", "juice", 15),
      ],
      garnish: ["Orange twist"],
      preparation: [
        "Shake all ingredients with ice.",
        "Strain into a chilled coupe.",
        "Express orange twist over the drink.",
      ],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "IBA Official Cocktails",
    sourceAuthor: "International Bartenders Association",
    sourceUrl: "https://iba-world.com/iba-cocktail/the-unforgettables/yellow-bird/",
    sourceRecipe: "IBA Yellow Bird (rum, Galliano, triple sec, lime)",
    recipeProvenance: "IBA Unforgettables list.",
    historicalNotes:
      "Jamaican rum meets Galliano's vanilla anise in a shaken sour—1960s international hotel culture in one glass.",
    rarity: "classic",
    funFact:
      "Galliano's tall vanilla profile makes the Yellow Bird taste sweeter than the spec suggests—shake hard to keep lime in balance.",
    yearInvented: 1960,
    regionOfOrigin: "Jamaica",
    alternateNames: [],
    cocktail: cocktail({
      name: "Yellow Bird",
      slug: "yellow-bird",
      glass: "Coupe",
      family: "Sour",
      method: "Shaken",
      tags: ["classic", "iba"],
      ingredients: [
        ing("rum-white", "White rum", "spirit", 30),
        ing("galliano", "Galliano", "liqueur", 15),
        ing("triple-sec", "Triple sec", "liqueur", 15),
        ing("lime-juice", "Lime juice", "juice", 15),
      ],
      garnish: ["Lime wheel"],
      preparation: [
        "Shake all ingredients with ice.",
        "Strain into a chilled coupe.",
        "Garnish with lime.",
      ],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "IBA Official Cocktails",
    sourceAuthor: "International Bartenders Association",
    sourceUrl: "https://iba-world.com/iba-cocktail/the-unforgettables/flamingo/",
    sourceRecipe: "IBA Flamingo (rum, apricot brandy, lime)",
    recipeProvenance: "IBA Unforgettables list.",
    historicalNotes:
      "Apricot brandy and white rum form a twin-spirit sour—the Flamingo name nods to pink-hued hotel-bar glamour of the mid-century.",
    rarity: "classic",
    funFact:
      "White rum plus apricot brandy yields a blush-pink sour without grenadine—the IBA spec keeps the fruit flavor dry and spirit-forward.",
    yearInvented: 1930,
    regionOfOrigin: "United States",
    alternateNames: [],
    cocktail: cocktail({
      name: "Flamingo",
      slug: "flamingo",
      glass: "Coupe",
      family: "Sour",
      method: "Shaken",
      tags: ["classic", "iba"],
      ingredients: [
        ing("rum-white", "White rum", "spirit", 45),
        ing("apricot-brandy", "Apricot brandy", "liqueur", 30),
        ing("lime-juice", "Lime juice", "juice", 15),
      ],
      garnish: ["Lime wheel"],
      preparation: [
        "Shake all ingredients with ice.",
        "Strain into a chilled coupe.",
        "Garnish with lime.",
      ],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Deauville (Calvados, triple sec, lemon)",
    recipeProvenance: "1930 Savoy spec.",
    historicalNotes:
      "Normandy apple brandy shaken with citrus and orange liqueur—Craddock's tribute to the Deauville resort crowd.",
    rarity: "well_known",
    funFact:
      "Calvados replaces gin in a sour skeleton here—Craddock wrote it for travelers who wanted Normandy in a coupe.",
    yearInvented: 1930,
    regionOfOrigin: "Normandy, France",
    alternateNames: [],
    cocktail: cocktail({
      name: "Deauville",
      slug: "deauville",
      glass: "Coupe",
      family: "Sour",
      method: "Shaken",
      tags: ["classic", "historical"],
      ingredients: [
        ing("apple-brandy", "Apple brandy", "spirit", 30),
        ing("triple-sec", "Triple sec", "liqueur", 30),
        ing("lemon-juice", "Lemon juice", "juice", 15),
      ],
      garnish: ["Lemon twist"],
      preparation: [
        "Shake all ingredients with ice.",
        "Strain into a chilled coupe.",
        "Garnish with lemon twist.",
      ],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Dubonnet Cocktail (gin, Dubonnet rouge)",
    recipeProvenance: "1930 Savoy; Dubonnet aromatized wine.",
    historicalNotes:
      "Queen Elizabeth The Queen Mother favored gin with Dubonnet—Craddock codified the two-ingredient stir in the Savoy.",
    rarity: "classic",
    funFact:
      "The late Queen Mother drank gin and Dubonnet daily before lunch—this two-part stir is royal habit turned bar standard.",
    yearInvented: 1930,
    regionOfOrigin: "London, UK",
    alternateNames: [],
    cocktail: cocktail({
      name: "Dubonnet Cocktail",
      slug: "dubonnet-cocktail",
      glass: "Coupe",
      family: "Aperitif",
      method: "Stirred",
      tags: ["classic", "historical"],
      ingredients: [
        ing("london-dry-gin", "London dry gin", "spirit", 45),
        ing("sweet-vermouth", "Sweet vermouth", "wine", 45),
      ],
      garnish: ["Orange twist"],
      preparation: [
        "Stir gin and Dubonnet-style aromatized wine with ice.",
        "Strain into a chilled coupe.",
        "Express orange twist; note house Dubonnet rouge when available.",
      ],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "How to Mix Drinks",
    sourceAuthor: "Jerry Thomas",
    sourceUrl: "",
    sourceRecipe: "Morning Glory Fizz (scotch, egg white, citrus, soda, absinthe rinse)",
    recipeProvenance: "1887 Bon Vivant companion / Thomas lineage.",
    historicalNotes:
      "A bracing hair-of-the-dog fizz—scotch, whole egg, dual citrus, and absinthe made it a Gilded Age morning ritual.",
    rarity: "classic",
    funFact:
      "Bartenders shook this fizz at dawn for weary revelers—absinthe rinse and scotch in the same glass was Victorian audacity.",
    yearInvented: 1888,
    regionOfOrigin: "United States",
    alternateNames: [],
    cocktail: cocktail({
      name: "Morning Glory Fizz",
      slug: "morning-glory-fizz",
      glass: "Collins",
      family: "Fizz",
      method: "Shaken",
      tags: ["historical", "classic"],
      ingredients: [
        ing("scotch", "Scotch whisky", "spirit", 45),
        ing("lemon-juice", "Lemon juice", "juice", 15),
        ing("lime-juice", "Lime juice", "juice", 15),
        ing("simple-syrup", "Simple syrup", "syrup", 15),
        ing("egg-white", "Egg white", "dairy-egg", 1, "white"),
        ing("absinthe", "Absinthe", "spirit", 1, "dash"),
        ing("club-soda", "Club soda", "mixer", 60),
      ],
      garnish: ["Lemon peel"],
      preparation: [
        "Dry-shake scotch, citrus, syrup, and egg white.",
        "Add ice and shake again; rinse glass with absinthe.",
        "Strain into a Collins glass and top with soda.",
      ],
    }),
  }),
  candidate({
    sourceTier: "high_quality_secondary",
    sourceTitle: "Death & Co",
    sourceAuthor: "David Kaplan et al.",
    sourceUrl: "",
    sourceRecipe: "Death & Co Purgatory (rye, green Chartreuse, dry vermouth)",
    recipeProvenance: "Modern Brooklyn speakeasy canon.",
    historicalNotes:
      "Chartreuse and rye in equal tension—Death & Co's name signals a Last Word cousin built for Manhattan whiskey drinkers.",
    rarity: "well_known",
    funFact:
      "Green Chartreuse and rye share herbal weight—this stirred trio drinks like a whiskey Last Word with dry vermouth softening the finish.",
    yearInvented: 2007,
    regionOfOrigin: "New York, USA",
    bar: "Death & Co",
    city: "New York",
    alternateNames: [],
    cocktail: cocktail({
      name: "Purgatory",
      slug: "purgatory",
      glass: "Coupe",
      family: "Aperitif",
      method: "Stirred",
      tags: ["modern-classic"],
      ingredients: [
        ing("rye-whiskey", "Rye whiskey", "spirit", 22.5),
        ing("green-chartreuse", "Green Chartreuse", "liqueur", 22.5),
        ing("dry-vermouth", "Dry vermouth", "wine", 22.5),
        ing("angostura-bitters", "Angostura bitters", "bitters", 1, "dash"),
      ],
      garnish: ["Lemon twist"],
      preparation: [
        "Stir all ingredients with ice.",
        "Strain into a chilled coupe.",
        "Garnish with lemon twist.",
      ],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Satan's Whiskers (straight)",
    recipeProvenance: "1930 Savoy spec.",
    historicalNotes:
      "Orange juice in a vermouth-gin split—Craddock offered 'straight' and 'curled' variants with Grand Marnier versus orange bitters.",
    rarity: "classic",
    funFact:
      "Craddock printed Satan's Whiskers two ways—Grand Marnier makes it 'Straight,' orange bitters make it 'Curled'—same cheeky name either path.",
    yearInvented: 1930,
    regionOfOrigin: "London, UK",
    alternateNames: ["Satan's Whiskers Straight"],
    cocktail: cocktail({
      name: "Satan's Whiskers",
      slug: "satan-whiskers",
      glass: "Coupe",
      family: "Sour",
      method: "Shaken",
      tags: ["classic", "historical"],
      ingredients: [
        ing("london-dry-gin", "London dry gin", "spirit", 30),
        ing("dry-vermouth", "Dry vermouth", "wine", 30),
        ing("orange-juice", "Orange juice", "juice", 30),
        ing("grand-marnier", "Grand Marnier", "liqueur", 15),
        ing("orange-bitters", "Orange bitters", "bitters", 1, "dash"),
      ],
      garnish: ["Orange twist"],
      preparation: [
        "Shake all ingredients with ice.",
        "Strain into a chilled coupe.",
        "Garnish with orange twist.",
      ],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Vermouth Cassis (dry vermouth, crème de cassis)",
    recipeProvenance: "1930 Savoy spec.",
    historicalNotes:
      "A French aperitif template—dry vermouth lengthened with blackcurrant liqueur before the Kir popularized wine-based versions.",
    rarity: "well_known",
    funFact:
      "Before the Kir switched to still wine, bartenders built this on dry vermouth—blackcurrant sweetness against herbal dry wine.",
    yearInvented: 1920,
    regionOfOrigin: "France",
    alternateNames: ["Vermouth Cassis"],
    cocktail: cocktail({
      name: "Vermouth Cassis",
      slug: "vermouth-cassiss",
      glass: "Wine glass",
      family: "Aperitif",
      method: "Built",
      tags: ["classic"],
      ingredients: [
        ing("dry-vermouth", "Dry vermouth", "wine", 45),
        ing("creme-de-cassis", "Crème de cassis", "liqueur", 15),
      ],
      garnish: ["Lemon twist"],
      preparation: [
        "Build vermouth and cassis over ice in a wine glass.",
        "Stir gently and garnish with lemon twist.",
      ],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "How to Mix Drinks",
    sourceAuthor: "Jerry Thomas",
    sourceUrl: "",
    sourceRecipe: "Whiskey Rickey (whiskey, lime, soda)",
    recipeProvenance: "1880s American highball; Rickey family legend.",
    historicalNotes:
      "Colonel Rickey's Washington DC order became the template—spirit, lime, soda, no sugar in the original whiskey version.",
    rarity: "classic",
    funFact:
      "The Rickey predates the Moscow Mule's vodka swap by decades—lime and soda over whiskey was Washington DC's summer default.",
    yearInvented: 1883,
    regionOfOrigin: "Washington, D.C., USA",
    alternateNames: ["Rickey"],
    cocktail: cocktail({
      name: "Whiskey Rickey",
      slug: "whiskey-rickey",
      glass: "Highball",
      family: "Highball",
      method: "Built",
      tags: ["classic", "historical"],
      ingredients: [
        ing("bourbon", "Bourbon", "spirit", 60),
        ing("lime-juice", "Lime juice", "juice", 15),
        ing("club-soda", "Club soda", "mixer", 90),
      ],
      garnish: ["Lime wedge"],
      preparation: [
        "Add whiskey and lime juice to a highball glass with ice.",
        "Top with chilled soda and stir once.",
        "Garnish with lime wedge.",
      ],
    }),
  }),
];
