import { candidate, cocktail } from "../lib/candidate.mjs";
import { ing } from "../lib/ing.mjs";

export const items = [
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "IBA Official Cocktails",
    sourceAuthor: "International Bartenders Association",
    sourceUrl: "https://iba-world.com/iba-cocktail/the-unforgettables/charleston/",
    sourceRecipe: "IBA Charleston (rum, lime, bitters, grenadine)",
    recipeProvenance: "IBA Unforgettables.",
    historicalNotes: "Bitters and grenadine tint a rum sour—1920s American name evoking Jazz Age South Carolina glamour.",
    rarity: "classic",
    funFact: "A few dashes of Angostura and grenadine turn a plain rum sour pink—IBA keeps the spec deliberately small.",
    yearInvented: 1920,
    regionOfOrigin: "United States",
    alternateNames: [],
    cocktail: cocktail({
      name: "Charleston",
      slug: "charleston",
      glass: "Coupe",
      family: "Sour",
      method: "Shaken",
      tags: ["classic", "iba"],
      ingredients: [
        ing("rum-white", "White rum", "spirit", 45),
        ing("lime-juice", "Lime juice", "juice", 15),
        ing("grenadine", "Grenadine", "syrup", 7.5),
        ing("angostura-bitters", "Angostura bitters", "bitters", 2, "dash"),
      ],
      garnish: ["Lime wheel"],
      preparation: ["Shake with ice.", "Strain into a chilled coupe.", "Garnish with lime."],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Harvard (cognac, sweet vermouth, soda)",
    recipeProvenance: "1930 Savoy printing.",
    historicalNotes: "Named for Harvard University—cognac and Italian vermouth topped with soda in a gentler Manhattan highball.",
    rarity: "classic",
    funFact: "Craddock's Harvard splits the difference between a Manhattan and a highball—soda keeps the cognac sessionable.",
    yearInvented: 1890,
    regionOfOrigin: "United States",
    alternateNames: [],
    cocktail: cocktail({
      name: "Harvard",
      slug: "harvard",
      glass: "Highball",
      family: "Highball",
      method: "Stirred",
      tags: ["classic", "historical"],
      ingredients: [
        ing("cognac", "Cognac", "spirit", 45),
        ing("sweet-vermouth", "Sweet vermouth", "wine", 45),
        ing("club-soda", "Club soda", "mixer", 30),
        ing("angostura-bitters", "Angostura bitters", "bitters", 2, "dash"),
      ],
      garnish: ["Lemon twist"],
      preparation: ["Stir cognac, vermouth, and bitters with ice.", "Strain over fresh ice.", "Top with soda and garnish."],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Horse's Neck (bourbon, ginger ale, lemon peel)",
    recipeProvenance: "1930 Savoy long drink.",
    historicalNotes: "A long lemon peel spirals over ginger ale and bourbon—the garnish shape gives the drink its equestrian name.",
    rarity: "well_known",
    funFact: "The Horse's Neck is mostly garnish theater: one long lemon spiral draped over ginger ale and bourbon in a highball.",
    yearInvented: 1890,
    regionOfOrigin: "United States",
    alternateNames: ["Horse's Neck"],
    cocktail: cocktail({
      name: "Horse's Neck",
      slug: "horse-neck",
      glass: "Highball",
      family: "Highball",
      method: "Built",
      tags: ["classic"],
      ingredients: [
        ing("bourbon", "Bourbon", "spirit", 60),
        ing("ginger-ale", "Ginger ale", "mixer", 120),
        ing("angostura-bitters", "Angostura bitters", "bitters", 2, "dash"),
      ],
      garnish: ["Long lemon peel spiral"],
      preparation: ["Build bourbon and bitters over ice in a highball.", "Top with ginger ale.", "Drape lemon peel over the rim."],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "IBA Official Cocktails",
    sourceAuthor: "International Bartenders Association",
    sourceUrl: "https://iba-world.com/iba-cocktail/the-unforgettables/kir/",
    sourceRecipe: "IBA Kir (white wine, crème de cassis)",
    recipeProvenance: "IBA Unforgettables; Canon Dijon aperitif.",
    historicalNotes: "Canon Félix Kir popularized crème de cassis with Aligoté—white wine replaced vermouth in post-war French aperitivo culture.",
    rarity: "well_known",
    funFact: "Mayor Canon Kir lent his name to blackcurrant wine after WWII—every French bistro still pours the template.",
    yearInvented: 1945,
    regionOfOrigin: "Dijon, France",
    creator: "Félix Kir",
    city: "Dijon",
    creationYear: 1945,
    alternateNames: [],
    cocktail: cocktail({
      name: "Kir",
      slug: "kir",
      glass: "Wine glass",
      family: "Aperitif",
      method: "Built",
      tags: ["classic", "iba"],
      ingredients: [
        ing("dry-white-wine", "Dry white wine", "wine", 120),
        ing("creme-de-cassis", "Crème de cassis", "liqueur", 15),
      ],
      garnish: ["Lemon twist"],
      preparation: ["Add cassis to a wine glass.", "Top with chilled white wine and stir gently."],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Palmetto (rum, vermouth, orange bitters)",
    recipeProvenance: "1930 Savoy; Manhattan structure with rum.",
    historicalNotes: "Rum replaces whiskey in a split-vermouth Manhattan—named for South Carolina's Palmetto state symbol.",
    rarity: "hidden_gem",
    funFact: "Split sweet and dry vermouth with aged rum drinks like a tropical Manhattan without leaving the coupe format.",
    yearInvented: 1930,
    regionOfOrigin: "United States",
    alternateNames: [],
    cocktail: cocktail({
      name: "Palmetto",
      slug: "palmetto",
      glass: "Coupe",
      family: "Manhattan",
      method: "Stirred",
      tags: ["classic", "historical"],
      ingredients: [
        ing("rum-aged", "Aged rum", "spirit", 45),
        ing("sweet-vermouth", "Sweet vermouth", "wine", 22.5),
        ing("dry-vermouth", "Dry vermouth", "wine", 22.5),
        ing("orange-bitters", "Orange bitters", "bitters", 2, "dash"),
      ],
      garnish: ["Orange twist"],
      preparation: ["Stir all ingredients with ice.", "Strain into a chilled coupe.", "Garnish with orange twist."],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "How to Mix Drinks",
    sourceAuthor: "Jerry Thomas",
    sourceUrl: "",
    sourceRecipe: "Coffee Cocktail (port, cognac, egg, sugar)",
    recipeProvenance: "1887 Bon Vivant; contains no coffee.",
    historicalNotes: "Named for its coffee-like appearance—port and cognac shaken with egg yolk mimic a latte cap despite zero caffeine.",
    rarity: "deep_cut",
    funFact: "Thomas's Coffee Cocktail never saw coffee beans—the name describes the foamy tan head from port, brandy, and egg.",
    yearInvented: 1887,
    regionOfOrigin: "United States",
    alternateNames: [],
    cocktail: cocktail({
      name: "Coffee Cocktail",
      slug: "coffee-cocktail",
      glass: "Coupe",
      family: "Flip",
      method: "Shaken",
      tags: ["historical", "classic"],
      ingredients: [
        ing("ruby-port", "Ruby port", "wine", 30),
        ing("cognac", "Cognac", "spirit", 30),
        ing("egg-yolk", "Egg yolk", "dairy-egg", 1, "yolk"),
        ing("simple-syrup", "Simple syrup", "syrup", 15),
        ing("nutmeg", "Nutmeg", "garnish", 1, "grating"),
      ],
      garnish: ["Grated nutmeg"],
      preparation: ["Shake all ingredients vigorously with ice.", "Strain into a chilled coupe.", "Grate nutmeg over the foam."],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "How to Mix Drinks",
    sourceAuthor: "Jerry Thomas",
    sourceUrl: "",
    sourceRecipe: "Blue Blazer (scotch, hot water, sugar, flaming toss)",
    recipeProvenance: "1862 Thomas showmanship spec.",
    historicalNotes: "Thomas tossed flaming scotch between mugs—performed for audiences rather than everyday service.",
    rarity: "deep_cut",
    funFact: "Jerry Thomas lit scotch on fire and poured it between two mugs in an arc—the original flair bartending stunt.",
    yearInvented: 1862,
    regionOfOrigin: "United States",
    creator: "Jerry Thomas",
    alternateNames: [],
    cocktail: cocktail({
      name: "Blue Blazer",
      slug: "blue-blazer",
      glass: "Mug",
      family: "Hot",
      method: "Built",
      tags: ["historical"],
      ingredients: [
        ing("scotch", "Scotch whisky", "spirit", 60),
        ing("hot-water", "Hot water", "mixer", 60),
        ing("simple-syrup", "Simple syrup", "syrup", 7.5),
        ing("lemon-peel", "Lemon peel", "garnish", 1, "twist"),
      ],
      garnish: ["Lemon twist"],
      preparation: [
        "Warm scotch, syrup, and water; ignite carefully if performing the classic toss.",
        "Pour between preheated mugs to mix.",
        "Serve hot with lemon twist; skip flames for home service.",
      ],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "How to Mix Drinks",
    sourceAuthor: "Jerry Thomas",
    sourceUrl: "",
    sourceRecipe: "Brandy Flip (brandy, egg, sugar, nutmeg)",
    recipeProvenance: "1862 flip family spec.",
    historicalNotes: "Whole egg and sugar enrich brandy in the flip template that predates cream liqueurs by a century.",
    rarity: "classic",
    funFact: "Flips once used hot pokers to froth ale—by Thomas's era brandy, egg, and nutmeg did the job shaken cold.",
    yearInvented: 1862,
    regionOfOrigin: "United States",
    alternateNames: [],
    cocktail: cocktail({
      name: "Brandy Flip",
      slug: "brandy-flip",
      glass: "Coupe",
      family: "Flip",
      method: "Shaken",
      tags: ["historical", "classic"],
      ingredients: [
        ing("brandy", "Brandy", "spirit", 60),
        ing("whole-egg", "Whole egg", "dairy-egg", 1, "egg"),
        ing("simple-syrup", "Simple syrup", "syrup", 15),
        ing("nutmeg", "Nutmeg", "garnish", 1, "grating"),
      ],
      garnish: ["Grated nutmeg"],
      preparation: ["Dry-shake then shake with ice.", "Strain into a chilled coupe.", "Grate nutmeg on top."],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Cooperstown (gin, dry vermouth, mint, orange bitters)",
    recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "Named for the New York baseball town—mint and orange bitters lift a dry Martini structure.",
    rarity: "hidden_gem",
    funFact: "Craddock added mint to a fifty-fifty Martini and named it for Cooperstown—baseball's hall of fame in a glass.",
    yearInvented: 1930,
    regionOfOrigin: "United States",
    alternateNames: [],
    cocktail: cocktail({
      name: "Cooperstown",
      slug: "cooperstown",
      glass: "Coupe",
      family: "Aperitif",
      method: "Stirred",
      tags: ["classic", "historical"],
      ingredients: [
        ing("london-dry-gin", "London dry gin", "spirit", 45),
        ing("dry-vermouth", "Dry vermouth", "wine", 45),
        ing("mint-leaves", "Mint leaves", "garnish", 6, "leaves"),
        ing("orange-bitters", "Orange bitters", "bitters", 2, "dash"),
      ],
      garnish: ["Mint sprig"],
      preparation: ["Stir gin, vermouth, and bitters with ice.", "Strain into a coupe.", "Slap mint and garnish."],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Chicago Fizz (rum, port, citrus, egg white, soda)",
    recipeProvenance: "1930 Savoy fizz variant.",
    historicalNotes: "Port and rum share the base with a split citrus fizz—Chicago's pre-Prohibition bar culture in a Collins glass.",
    rarity: "hidden_gem",
    funFact: "Port in a fizz is rare today—Craddock's Chicago version splits rum and ruby port before the soda top.",
    yearInvented: 1900,
    regionOfOrigin: "Chicago, USA",
    alternateNames: [],
    cocktail: cocktail({
      name: "Chicago Fizz",
      slug: "chicago-fizz",
      glass: "Collins",
      family: "Fizz",
      method: "Shaken",
      tags: ["historical", "classic"],
      ingredients: [
        ing("rum-white", "White rum", "spirit", 30),
        ing("ruby-port", "Ruby port", "wine", 30),
        ing("lemon-juice", "Lemon juice", "juice", 15),
        ing("lime-juice", "Lime juice", "juice", 15),
        ing("simple-syrup", "Simple syrup", "syrup", 15),
        ing("egg-white", "Egg white", "dairy-egg", 1, "white"),
        ing("club-soda", "Club soda", "mixer", 60),
      ],
      garnish: ["Nutmeg"],
      preparation: ["Dry-shake, then shake with ice.", "Strain into Collins over ice.", "Top with soda and nutmeg."],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Artillery (sweet vermouth, gin, bitters)",
    recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "Sweet vermouth leads with gin as modifier—named for the punch of its fortified wine base.",
    rarity: "hidden_gem",
    funFact: "Reverse the Manhattan ratios and you get Artillery—vermouth-heavy, gin as seasoning.",
    yearInvented: 1930,
    regionOfOrigin: "London, UK",
    alternateNames: [],
    cocktail: cocktail({
      name: "Artillery",
      slug: "artillery",
      glass: "Coupe",
      family: "Manhattan",
      method: "Stirred",
      tags: ["historical"],
      ingredients: [
        ing("sweet-vermouth", "Sweet vermouth", "wine", 45),
        ing("london-dry-gin", "London dry gin", "spirit", 22.5),
        ing("angostura-bitters", "Angostura bitters", "bitters", 2, "dash"),
      ],
      garnish: ["Lemon twist"],
      preparation: ["Stir with ice.", "Strain into a chilled coupe.", "Garnish with lemon twist."],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Ford Cocktail (gin, dry vermouth, Benedictine)",
    recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "A dry Martini sweetened with Benedictine—named for automotive pioneer Henry Ford's era.",
    rarity: "hidden_gem",
    funFact: "One barspoon of Benedictine turns a dry Martini into the Ford—herbal honey without full sweetness.",
    yearInvented: 1930,
    regionOfOrigin: "United States",
    alternateNames: [],
    cocktail: cocktail({
      name: "Ford Cocktail",
      slug: "ford-cocktail",
      glass: "Coupe",
      family: "Aperitif",
      method: "Stirred",
      tags: ["historical"],
      ingredients: [
        ing("london-dry-gin", "London dry gin", "spirit", 45),
        ing("dry-vermouth", "Dry vermouth", "wine", 45),
        ing("benedictine", "Benedictine", "liqueur", 7.5),
        ing("angostura-bitters", "Angostura bitters", "bitters", 1, "dash"),
      ],
      garnish: ["Orange twist"],
      preparation: ["Stir all ingredients with ice.", "Strain into a chilled coupe.", "Garnish with orange twist."],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Old Waldorf-Astoria Bar Book",
    sourceAuthor: "Albert Stevens Crockett",
    sourceUrl: "",
    sourceRecipe: "Golden Cadillac (Galliano, crème de cacao, cream)",
    recipeProvenance: "1950s California dessert cocktail.",
    historicalNotes: "Invented after a Cadillac purchase at Los Angeles' Poor Red's—Galliano and white cacao define the after-dinner sipper.",
    rarity: "well_known",
    funFact: "Poor Red's in California claims a newly purchased Cadillac inspired this cream-and-Galliano dessert drink in 1952.",
    yearInvented: 1952,
    regionOfOrigin: "California, USA",
    bar: "Poor Red's",
    city: "El Monte",
    creationYear: 1952,
    alternateNames: [],
    cocktail: cocktail({
      name: "Golden Cadillac",
      slug: "golden-cadillac",
      glass: "Coupe",
      family: "Flip",
      method: "Shaken",
      tags: ["classic"],
      ingredients: [
        ing("galliano", "Galliano", "liqueur", 30),
        ing("creme-de-cacao-white", "White crème de cacao", "liqueur", 30),
        ing("heavy-cream", "Heavy cream", "dairy-egg", 30),
      ],
      garnish: ["Nutmeg"],
      preparation: ["Shake with ice.", "Strain into a chilled coupe.", "Grate nutmeg if desired."],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Metropole (cognac, dry vermouth, syrup, bitters)",
    recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "Named for the Hotel Metropole—cognac and dry vermouth with a touch of syrup bridge Manhattan and Martini camps.",
    rarity: "hidden_gem",
    funFact: "Hotel Metropole guests drank cognac like Americans drank rye—this spec splits the difference with dry vermouth.",
    yearInvented: 1930,
    regionOfOrigin: "London, UK",
    alternateNames: [],
    cocktail: cocktail({
      name: "Metropole",
      slug: "metropole",
      glass: "Coupe",
      family: "Manhattan",
      method: "Stirred",
      tags: ["historical"],
      ingredients: [
        ing("cognac", "Cognac", "spirit", 45),
        ing("dry-vermouth", "Dry vermouth", "wine", 45),
        ing("simple-syrup", "Simple syrup", "syrup", 7.5),
        ing("angostura-bitters", "Angostura bitters", "bitters", 2, "dash"),
      ],
      garnish: ["Lemon twist"],
      preparation: ["Stir with ice.", "Strain into a chilled coupe.", "Garnish with lemon twist."],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Opera (gin, maraschino, cream, orange bitters)",
    recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "A dessert-leaning gin cocktail with cream and maraschino—named for London's theatrical district.",
    rarity: "deep_cut",
    funFact: "Maraschino and cream with gin drinks like a cherry trifle—Craddock filed it under opera-house intermission sippers.",
    yearInvented: 1930,
    regionOfOrigin: "London, UK",
    alternateNames: [],
    cocktail: cocktail({
      name: "Opera",
      slug: "opera",
      glass: "Coupe",
      family: "Flip",
      method: "Shaken",
      tags: ["historical"],
      ingredients: [
        ing("london-dry-gin", "London dry gin", "spirit", 30),
        ing("maraschino-liqueur", "Maraschino liqueur", "liqueur", 15),
        ing("heavy-cream", "Heavy cream", "dairy-egg", 30),
        ing("orange-bitters", "Orange bitters", "bitters", 2, "dash"),
      ],
      garnish: ["Orange twist"],
      preparation: ["Shake with ice.", "Strain into a chilled coupe.", "Garnish with orange twist."],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Poet's Dream (gin, vermouths, absinthe)",
    recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "Split vermouths and absinthe surround gin—a fin-de-siècle flavor profile Craddock labeled for literary bohemians.",
    rarity: "hidden_gem",
    funFact: "Absinthe rinse energy without the rinse—Poet's Dream keeps the herbaceous note in the stirred mix.",
    yearInvented: 1930,
    regionOfOrigin: "London, UK",
    alternateNames: [],
    cocktail: cocktail({
      name: "Poet's Dream",
      slug: "poets-dream",
      glass: "Coupe",
      family: "Aperitif",
      method: "Stirred",
      tags: ["historical"],
      ingredients: [
        ing("london-dry-gin", "London dry gin", "spirit", 30),
        ing("dry-vermouth", "Dry vermouth", "wine", 30),
        ing("sweet-vermouth", "Sweet vermouth", "wine", 15),
        ing("absinthe", "Absinthe", "spirit", 7.5),
      ],
      garnish: ["Lemon twist"],
      preparation: ["Stir with ice.", "Strain into a chilled coupe.", "Garnish with lemon twist."],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "How to Mix Drinks",
    sourceAuthor: "Jerry Thomas",
    sourceUrl: "",
    sourceRecipe: "Port Flip (port, egg, sugar, nutmeg)",
    recipeProvenance: "1862 flip family.",
    historicalNotes: "Ruby port substitutes for spirit in the flip template—Victorian after-dinner richness.",
    rarity: "deep_cut",
    funFact: "Port flips trade spirit heat for wine sweetness—Thomas treated them as dessert in a coupe.",
    yearInvented: 1862,
    regionOfOrigin: "United States",
    alternateNames: [],
    cocktail: cocktail({
      name: "Port Flip",
      slug: "port-flip",
      glass: "Coupe",
      family: "Flip",
      method: "Shaken",
      tags: ["historical"],
      ingredients: [
        ing("ruby-port", "Ruby port", "wine", 60),
        ing("whole-egg", "Whole egg", "dairy-egg", 1, "egg"),
        ing("simple-syrup", "Simple syrup", "syrup", 15),
        ing("nutmeg", "Nutmeg", "garnish", 1, "grating"),
      ],
      garnish: ["Grated nutmeg"],
      preparation: ["Shake vigorously with ice.", "Strain into a chilled coupe.", "Grate nutmeg."],
    }),
  }),
];
