import { candidate, cocktail } from "../lib/candidate.mjs";
import { ing } from "../lib/ing.mjs";

export const items = [
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Princeton (old tom gin, port, orange bitters)",
    recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "Old tom gin's sweetness meets ruby port—named for the New Jersey university like many Ivy-themed Craddock drinks.",
    rarity: "hidden_gem",
    funFact: "Old tom gin makes the Princeton sweeter than a dry-gin port split—Craddock assumed richer gin stock.",
    yearInvented: 1930,
    regionOfOrigin: "United States",
    alternateNames: [],
    cocktail: cocktail({ name: "Princeton", slug: "princeton", glass: "Coupe", family: "Aperitif", method: "Stirred", tags: ["historical"], ingredients: [ing("old-tom-gin", "Old tom gin", "spirit", 45), ing("ruby-port", "Ruby port", "wine", 45), ing("orange-bitters", "Orange bitters", "bitters", 2, "dash")], garnish: ["Orange twist"], preparation: ["Stir with ice.", "Strain into a chilled coupe.", "Garnish with orange twist."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Tipperary (Irish whiskey, sweet vermouth, green Chartreuse)",
    recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "Irish whiskey Manhattan with Chartreuse—named for the Irish county during political ferment of the 1920s.",
    rarity: "classic",
    funFact: "Green Chartreuse turns an Irish whiskey Manhattan into something herbal enough to split a room of purists.",
    yearInvented: 1920,
    regionOfOrigin: "Ireland",
    alternateNames: ["Tipperary"],
    cocktail: cocktail({ name: "Tipperary Cocktail", slug: "tipperary-cocktail", glass: "Coupe", family: "Manhattan", method: "Stirred", tags: ["classic", "historical"], ingredients: [ing("irish-whiskey", "Irish whiskey", "spirit", 45), ing("sweet-vermouth", "Sweet vermouth", "wine", 30), ing("green-chartreuse", "Green Chartreuse", "liqueur", 15)], garnish: ["Orange twist"], preparation: ["Stir with ice.", "Strain into a chilled coupe.", "Garnish with orange twist."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "El Floridita / IBA lineage",
    sourceAuthor: "Constantino Ribalaigua Vert",
    sourceUrl: "",
    sourceRecipe: "Hemingway Special / Papa Doble (rum, maraschino, grapefruit, lime, no sugar)",
    recipeProvenance: "Floridita house spec for Ernest Hemingway.",
    historicalNotes: "Ribalaigua tailored a sugarless daiquiri double for Hemingway—grapefruit and maraschino replace simple syrup.",
    rarity: "well_known",
    funFact: "Hemingway's diabetes drove the sugarless double—Floridita staff called it the Papa Doble before the IBA renamed it Hemingway Special.",
    yearInvented: 1937,
    regionOfOrigin: "Havana, Cuba",
    creator: "Constantino Ribalaigua Vert",
    bar: "El Floridita",
    city: "Havana",
    creationYear: 1937,
    alternateNames: ["Papa Doble"],
    cocktail: cocktail({ name: "Hemingway Special", slug: "hemingway-special", glass: "Coupe", family: "Sour", method: "Shaken", tags: ["classic", "iba"], ingredients: [ing("rum-white", "White rum", "spirit", 60), ing("maraschino-liqueur", "Maraschino liqueur", "liqueur", 15), ing("grapefruit-juice", "Grapefruit juice", "juice", 30), ing("lime-juice", "Lime juice", "juice", 15)], garnish: ["Lime wheel"], preparation: ["Shake hard with ice.", "Strain into a chilled coupe.", "Garnish with lime."] }),
  }),
  candidate({
    sourceTier: "other_verified",
    sourceTitle: "Mexican bar canon",
    sourceAuthor: "Documented Mexico City recipe",
    sourceUrl: "",
    sourceRecipe: "Periodista (tequila, coffee liqueur, lime)",
    recipeProvenance: "Journalists' bar template in Mexican cocktail literature.",
    historicalNotes: "Tequila, coffee liqueur, and lime—a bitter-edged highball associated with Mexico City press rooms.",
    rarity: "hidden_gem",
    funFact: "Periodista translates to journalist—Mexico City's reporters reportedly ordered tequila and coffee liqueur with lime after deadline.",
    yearInvented: 1950,
    regionOfOrigin: "Mexico City, Mexico",
    alternateNames: [],
    cocktail: cocktail({ name: "Periodista", slug: "periodista", glass: "Coupe", family: "Sour", method: "Shaken", tags: ["classic"], ingredients: [ing("tequila-blanco", "Tequila blanco", "spirit", 45), ing("coffee-liqueur", "Coffee liqueur", "liqueur", 22.5), ing("lime-juice", "Lime juice", "juice", 15)], garnish: ["Lime wheel"], preparation: ["Shake with ice.", "Strain into a chilled coupe.", "Garnish with lime."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "How to Mix Drinks",
    sourceAuthor: "Jerry Thomas",
    sourceUrl: "",
    sourceRecipe: "Milk Punch (brandy, milk, sugar, vanilla)",
    recipeProvenance: "1862 clarified milk punch lineage.",
    historicalNotes: "Milk clarifies when acid curdles casein—Thomas documented the brandy template that Southern hosts bottled for holidays.",
    rarity: "classic",
    funFact: "Clarified milk punch can sit bottled for months—the curdled milk strains out leaving silky brandy and spice.",
    yearInvented: 1862,
    regionOfOrigin: "United States",
    alternateNames: ["Clarified Milk Punch"],
    cocktail: cocktail({ name: "Milk Punch", slug: "milk-punch", glass: "Coupe", family: "Punch", method: "Shaken", tags: ["historical", "classic"], ingredients: [ing("brandy", "Brandy", "spirit", 60), ing("whole-milk", "Whole milk", "dairy-egg", 90), ing("simple-syrup", "Simple syrup", "syrup", 15), ing("vanilla-syrup", "Vanilla syrup", "syrup", 7.5), ing("nutmeg", "Nutmeg", "garnish", 1, "grating")], garnish: ["Grated nutmeg"], preparation: ["Shake brandy, milk, and syrups with ice.", "Strain into a coupe.", "Grate nutmeg; clarify for bottled service if desired."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Queen's (gin, ruby port, lemon, raspberry)",
    recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "Gin and port split base with raspberry cordial—Craddock's royal naming convention for split-base sours.",
    rarity: "hidden_gem",
    funFact: "Ruby port and gin with raspberry reads like a British summer pudding turned cocktail.",
    yearInvented: 1930,
    regionOfOrigin: "London, UK",
    alternateNames: ["Queen's Cocktail"],
    cocktail: cocktail({ name: "Queen's", slug: "queens", glass: "Coupe", family: "Sour", method: "Shaken", tags: ["historical"], ingredients: [ing("london-dry-gin", "London dry gin", "spirit", 30), ing("ruby-port", "Ruby port", "wine", 30), ing("lemon-juice", "Lemon juice", "juice", 15), ing("raspberry-syrup", "Raspberry syrup", "syrup", 7.5)], garnish: ["Raspberry"], preparation: ["Shake with ice.", "Strain into a chilled coupe.", "Garnish with raspberry."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "IBA Official Cocktails",
    sourceAuthor: "International Bartenders Association",
    sourceUrl: "https://iba-world.com/iba-cocktail/the-unforgettables/rose/",
    sourceRecipe: "IBA Rose (dry vermouth, kirsch, raspberry syrup)",
    recipeProvenance: "IBA Unforgettables.",
    historicalNotes: "Kirschwasser and dry vermouth with raspberry—distinct from the gin-based Rose cocktail slug elsewhere in this batch.",
    rarity: "classic",
    funFact: "The IBA Rose is vermouth-forward with cherry eau-de-vie—no gin despite the delicate pink name.",
    yearInvented: 1920,
    regionOfOrigin: "France",
    alternateNames: [],
    cocktail: cocktail({ name: "Rose Cocktail", slug: "rose-cocktail", glass: "Coupe", family: "Aperitif", method: "Stirred", tags: ["classic", "iba"], ingredients: [ing("dry-vermouth", "Dry vermouth", "wine", 45), ing("apple-brandy", "Apple brandy", "spirit", 15), ing("raspberry-syrup", "Raspberry syrup", "syrup", 15)], garnish: ["Lemon twist"], preparation: ["Stir with ice.", "Strain into a chilled coupe.", "Garnish with lemon twist."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Star (apple brandy, sweet vermouth)",
    recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "Apple brandy Manhattan—American applejack culture filtered through London hotel bars.",
    rarity: "hidden_gem",
    funFact: "Two ingredients, equal parts—apple brandy and sweet vermouth drinks like a autumn Manhattan.",
    yearInvented: 1930,
    regionOfOrigin: "United States",
    alternateNames: ["Star"],
    cocktail: cocktail({ name: "Star Cocktail", slug: "star-cocktail", glass: "Coupe", family: "Manhattan", method: "Stirred", tags: ["historical"], ingredients: [ing("apple-brandy", "Apple brandy", "spirit", 45), ing("sweet-vermouth", "Sweet vermouth", "wine", 45), ing("angostura-bitters", "Angostura bitters", "bitters", 1, "dash")], garnish: ["Cherry"], preparation: ["Stir with ice.", "Strain into a chilled coupe.", "Garnish with cherry."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Imperial Fizz (gin, lemon, egg white, champagne)",
    recipeProvenance: "1930 Savoy fizz.",
    historicalNotes: "Champagne tops a gin fizz—Imperial signaling the sparkling crown on a standard sour fizz.",
    rarity: "classic",
    funFact: "Skip the soda in a gin fizz and top with champagne instead—you get the Imperial template Craddock printed.",
    yearInvented: 1930,
    regionOfOrigin: "London, UK",
    alternateNames: [],
    cocktail: cocktail({ name: "Imperial Fizz", slug: "imperial-fizz", glass: "Flute", family: "Fizz", method: "Shaken", tags: ["classic", "champagne"], ingredients: [ing("london-dry-gin", "London dry gin", "spirit", 45), ing("lemon-juice", "Lemon juice", "juice", 15), ing("simple-syrup", "Simple syrup", "syrup", 15), ing("egg-white", "Egg white", "dairy-egg", 1, "white"), ing("champagne", "Champagne", "wine", 60)], garnish: ["Lemon twist"], preparation: ["Dry-shake, then shake with ice.", "Strain into a flute.", "Top with champagne."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Nightcap (cognac, white crème de cacao, cream)",
    recipeProvenance: "1930 Savoy dessert cocktail.",
    historicalNotes: "After-dinner wind-down—cognac and white cacao with cream in a small chilled format.",
    rarity: "hidden_gem",
    funFact: "Craddock's Nightcap predates the Golden Cadillac—cognac instead of Galliano for a quieter bedtime sip.",
    yearInvented: 1930,
    regionOfOrigin: "London, UK",
    alternateNames: [],
    cocktail: cocktail({ name: "Nightcap", slug: "nightcap", glass: "Coupe", family: "Flip", method: "Shaken", tags: ["historical"], ingredients: [ing("cognac", "Cognac", "spirit", 30), ing("creme-de-cacao-white", "White crème de cacao", "liqueur", 30), ing("heavy-cream", "Heavy cream", "dairy-egg", 30)], garnish: ["Nutmeg"], preparation: ["Shake with ice.", "Strain into a chilled coupe.", "Grate nutmeg lightly."] }),
  }),
  candidate({
    sourceTier: "high_quality_secondary",
    sourceTitle: "Beachbum Berry Remixed",
    sourceAuthor: "Jeff Berry",
    sourceUrl: "",
    sourceRecipe: "King Cole (rum, fassionola substitute, lime)",
    recipeProvenance: "Berry reconstruction; grenadine and passion fruit stand in for fassionola.",
    historicalNotes: "Don the Beachcomber's King Cole used house fassionola—modern builds split grenadine and passion fruit syrup.",
    rarity: "deep_cut",
    funFact: "Fassionola syrup vanished from production—today's King Cole rebuilds the red tropical note with grenadine and passion fruit.",
    yearInvented: 1937,
    regionOfOrigin: "Hollywood, USA",
    alternateNames: [],
    cocktail: cocktail({ name: "King Cole", slug: "king-cole", glass: "Tiki mug", family: "Tiki", method: "Blend", tags: ["tiki", "historical"], ingredients: [ing("rum-dark", "Dark rum", "spirit", 45), ing("lime-juice", "Lime juice", "juice", 22.5), ing("grenadine", "Grenadine", "syrup", 15), ing("passion-fruit-syrup", "Passion fruit syrup", "syrup", 15), ing("falernum", "Falernum", "liqueur", 7.5)], garnish: ["Mint sprig"], preparation: ["Blend with crushed ice.", "Pour into a tiki mug.", "Garnish with mint."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Man O' War (bourbon, sweet vermouth, lemon, grenadine)",
    recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "Named for the WWI naval slogan—bourbon Manhattan with lemon and grenadine for a sour tilt.",
    rarity: "hidden_gem",
    funFact: "Craddock named this for the Great War recruitment poster—bourbon and vermouth with a sour's citrus.",
    yearInvented: 1930,
    regionOfOrigin: "United States",
    alternateNames: ["Man O'War"],
    cocktail: cocktail({ name: "Man O' War", slug: "man-o-war", glass: "Coupe", family: "Sour", method: "Shaken", tags: ["historical"], ingredients: [ing("bourbon", "Bourbon", "spirit", 45), ing("sweet-vermouth", "Sweet vermouth", "wine", 30), ing("lemon-juice", "Lemon juice", "juice", 15), ing("grenadine", "Grenadine", "syrup", 7.5)], garnish: ["Lemon twist"], preparation: ["Shake with ice.", "Strain into a chilled coupe.", "Garnish with lemon twist."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy Royal Hawaiian (gin, pineapple, lemon, orgeat)",
    recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "Pre-tiki hotel drink—gin with pineapple and orgeat anticipates later Polynesian pop culture cocktails.",
    rarity: "well_known",
    funFact: "Gin and orgeat rarely meet outside this spec—pineapple bridges the almond sweetness before tiki took over.",
    yearInvented: 1930,
    regionOfOrigin: "Honolulu, Hawaii, USA",
    alternateNames: [],
    cocktail: cocktail({ name: "Royal Hawaiian", slug: "royal-hawaiian", glass: "Coupe", family: "Sour", method: "Shaken", tags: ["classic", "tiki"], ingredients: [ing("london-dry-gin", "London dry gin", "spirit", 45), ing("pineapple-juice", "Pineapple juice", "juice", 30), ing("lemon-juice", "Lemon juice", "juice", 15), ing("orgeat", "Orgeat", "syrup", 15)], garnish: ["Pineapple wedge"], preparation: ["Shake with ice.", "Strain into a chilled coupe.", "Garnish with pineapple."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Old Waldorf-Astoria Bar Book",
    sourceAuthor: "Albert Stevens Crockett",
    sourceUrl: "",
    sourceRecipe: "San Francisco (crème de banane, vodka, pineapple, cream)",
    recipeProvenance: "Waldorf-Astoria lineage.",
    historicalNotes: "Banana liqueur and cream define a 1970s dessert cocktail named for the California city.",
    rarity: "well_known",
    funFact: "Banana liqueur plus cream reads like a liquid dessert—Waldorf-era specs lean heavily on crème de banane.",
    yearInvented: 1960,
    regionOfOrigin: "San Francisco, USA",
    alternateNames: [],
    cocktail: cocktail({ name: "San Francisco", slug: "san-francisco", glass: "Coupe", family: "Flip", method: "Shaken", tags: ["classic"], ingredients: [ing("banana-liqueur", "Banana liqueur", "liqueur", 30), ing("vodka", "Vodka", "spirit", 30), ing("pineapple-juice", "Pineapple juice", "juice", 30), ing("heavy-cream", "Heavy cream", "dairy-egg", 15)], garnish: ["Pineapple wedge"], preparation: ["Shake with ice.", "Strain into a chilled coupe.", "Garnish with pineapple."] }),
  }),
  candidate({
    sourceTier: "high_quality_secondary",
    sourceTitle: "Death & Co",
    sourceAuthor: "David Kaplan et al.",
    sourceUrl: "",
    sourceRecipe: "Left Bank (gin, St-Germain, Sauvignon Blanc)",
    recipeProvenance: "Death & Co modern classic.",
    historicalNotes: "Elderflower liqueur and crisp white wine soften gin—a Lower East Side neo-speakeasy staple.",
    rarity: "well_known",
    funFact: "Death & Co cut gin with Sauvignon Blanc and elderflower—Lower East Side drinkers called it the Left Bank.",
    yearInvented: 2007,
    regionOfOrigin: "New York, USA",
    bar: "Death & Co",
    city: "New York",
    creationYear: 2007,
    alternateNames: [],
    cocktail: cocktail({ name: "Left Bank", slug: "left-bank", glass: "Coupe", family: "Sour", method: "Shaken", tags: ["modern-classic"], ingredients: [ing("london-dry-gin", "London dry gin", "spirit", 45), ing("elderflower-liqueur", "Elderflower liqueur", "liqueur", 22.5), ing("dry-white-wine", "Dry white wine", "wine", 22.5), ing("lemon-juice", "Lemon juice", "juice", 15)], garnish: ["Lemon twist"], preparation: ["Shake gin, elderflower, and lemon with ice.", "Strain into a coupe.", "Float or stir in chilled wine; garnish."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "The Savoy Cocktail Book",
    sourceAuthor: "Harry Craddock",
    sourceUrl: "",
    sourceRecipe: "Savoy London Sour (gin, lemon, triple sec, red wine float)",
    recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "New York Sour's cousin with gin—lemon sour topped with a red wine float for color and tannin.",
    rarity: "hidden_gem",
    funFact: "Float claret on a gin sour and Craddock called it London—tannin on citrus without changing the base spirit.",
    yearInvented: 1930,
    regionOfOrigin: "London, UK",
    alternateNames: [],
    cocktail: cocktail({ name: "London Sour", slug: "london-sour", glass: "Rocks", family: "Sour", method: "Shaken", tags: ["historical"], ingredients: [ing("london-dry-gin", "London dry gin", "spirit", 45), ing("lemon-juice", "Lemon juice", "juice", 22.5), ing("triple-sec", "Triple sec", "liqueur", 15), ing("simple-syrup", "Simple syrup", "syrup", 7.5), ing("red-wine", "Red wine", "wine", 15)], garnish: ["Lemon wheel"], preparation: ["Shake gin, citrus, triple sec, and syrup with ice.", "Strain over ice.", "Float red wine on top."] }),
  }),
  candidate({
    sourceTier: "high_quality_secondary",
    sourceTitle: "Smuggler's Cove",
    sourceAuthor: "Martin Cate & Rebecca Cate",
    sourceUrl: "",
    sourceRecipe: "Smuggler's Cove Luau Grog",
    recipeProvenance: "Modern tiki canon grog blend.",
    historicalNotes: "Multi-rum grog with tropical citrus—luau service format from mid-century Hawaiian hospitality.",
    rarity: "well_known",
    funFact: "Luau grogs batch rum for crowds—Smuggler's Cove scales the spec for home mugs without losing spice.",
    yearInvented: 1950,
    regionOfOrigin: "Hawaii, USA",
    alternateNames: [],
    cocktail: cocktail({ name: "Luau Grog", slug: "luau-grog", glass: "Tiki mug", family: "Tiki", method: "Blend", tags: ["tiki", "classic"], ingredients: [ing("rum-white", "White rum", "spirit", 30), ing("rum-dark", "Dark rum", "spirit", 30), ing("lime-juice", "Lime juice", "juice", 22.5), ing("falernum", "Falernum", "liqueur", 15), ing("passion-fruit-syrup", "Passion fruit syrup", "syrup", 15), ing("club-soda", "Club soda", "mixer", 30)], garnish: ["Mint sprig", "edible flower"], preparation: ["Blend with crushed ice.", "Pour into a tiki mug.", "Top with splash of soda; garnish."] }),
  }),
];
