import { candidate, cocktail } from "../lib/candidate.mjs";
import { ing } from "../lib/ing.mjs";

export const items = [
  candidate({
    sourceTier: "primary_authoritative", sourceTitle: "The Savoy Cocktail Book", sourceAuthor: "Harry Craddock", sourceUrl: "",
    sourceRecipe: "Savoy Honolulu Cooler (gin, pineapple, lemon, soda)", recipeProvenance: "1930 Savoy long drink.",
    historicalNotes: "Gin cooler with pineapple and lemon—pre-tiki Hawaiian hotel bar template.", rarity: "hidden_gem",
    funFact: "Craddock printed Honolulu Cooler before Donn Beach imported Polynesian kitsch—gin and pineapple, not rum.",
    yearInvented: 1930, regionOfOrigin: "Honolulu, Hawaii, USA", alternateNames: [],
    cocktail: cocktail({ name: "Honolulu Cooler", slug: "honolulu-cooler", glass: "Collins", family: "Highball", method: "Shaken", tags: ["classic"], ingredients: [ing("london-dry-gin", "London dry gin", "spirit", 45), ing("pineapple-juice", "Pineapple juice", "juice", 30), ing("lemon-juice", "Lemon juice", "juice", 15), ing("simple-syrup", "Simple syrup", "syrup", 15), ing("club-soda", "Club soda", "mixer", 60)], garnish: ["Pineapple wedge", "mint"], preparation: ["Shake gin, juices, and syrup with ice.", "Strain into Collins over ice.", "Top with soda and garnish."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative", sourceTitle: "The Savoy Cocktail Book", sourceAuthor: "Harry Craddock", sourceUrl: "",
    sourceRecipe: "Savoy Havana Cooler (rum, lime, mint, soda)", recipeProvenance: "1930 Savoy cooler.",
    historicalNotes: "Rum mojito-adjacent cooler with soda—Cuban template via London hotel printing.", rarity: "well_known",
    funFact: "Mint, lime, rum, and soda in a Collins—Craddock's Havana Cooler predates the mojito's global fame.",
    yearInvented: 1930, regionOfOrigin: "Cuba", alternateNames: [],
    cocktail: cocktail({ name: "Havana Cooler", slug: "havana-cooler", glass: "Collins", family: "Highball", method: "Built", tags: ["classic"], ingredients: [ing("rum-white", "White rum", "spirit", 45), ing("lime-juice", "Lime juice", "juice", 22.5), ing("simple-syrup", "Simple syrup", "syrup", 15), ing("mint-leaves", "Mint leaves", "garnish", 8, "leaves"), ing("club-soda", "Club soda", "mixer", 90)], garnish: ["Mint sprig"], preparation: ["Muddle mint with syrup and lime in glass.", "Add rum and ice; top with soda.", "Garnish with mint."] }),
  }),
  candidate({
    sourceTier: "high_quality_secondary", sourceTitle: "Smuggler's Cove", sourceAuthor: "Martin Cate & Rebecca Cate", sourceUrl: "",
    sourceRecipe: "Martinique Sour (rhum agricole, lime, orange curaçao, orgeat)", recipeProvenance: "French Caribbean sour template.",
    historicalNotes: "Rhum agricole sour with orgeat—Martinique's answer to the daiquiri with almond sweetness.", rarity: "well_known",
    funFact: "Agricole rum's grassy funk needs orgeat to round the edges—Martinique bars treat this as the house sour.",
    yearInvented: null, regionOfOrigin: "Martinique", alternateNames: [],
    cocktail: cocktail({ name: "Martinique Sour", slug: "martinique-sour", glass: "Coupe", family: "Sour", method: "Shaken", tags: ["classic", "tiki"], ingredients: [ing("rhum-agricole", "Rhum agricole", "spirit", 60), ing("lime-juice", "Lime juice", "juice", 22.5), ing("orange-curacao", "Orange curaçao", "liqueur", 15), ing("orgeat", "Orgeat", "syrup", 7.5)], garnish: ["Lime wheel"], preparation: ["Shake with ice.", "Strain into a chilled coupe.", "Garnish with lime."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative", sourceTitle: "The Savoy Cocktail Book", sourceAuthor: "Harry Craddock", sourceUrl: "",
    sourceRecipe: "Savoy Park Avenue (gin, pineapple, sweet vermouth, orange juice)", recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "Manhattan-adjacent gin cocktail with pineapple—named for New York's luxury corridor.", rarity: "hidden_gem",
    funFact: "Sweet vermouth and pineapple in a gin base drinks like a Waldorf hotel lounge special.",
    yearInvented: 1930, regionOfOrigin: "New York, USA", alternateNames: [],
    cocktail: cocktail({ name: "Park Avenue", slug: "park-avenue", glass: "Coupe", family: "Sour", method: "Shaken", tags: ["historical"], ingredients: [ing("london-dry-gin", "London dry gin", "spirit", 45), ing("sweet-vermouth", "Sweet vermouth", "wine", 22.5), ing("pineapple-juice", "Pineapple juice", "juice", 22.5), ing("orange-juice", "Orange juice", "juice", 15)], garnish: ["Orange twist"], preparation: ["Shake with ice.", "Strain into a chilled coupe.", "Garnish with orange twist."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative", sourceTitle: "The Savoy Cocktail Book", sourceAuthor: "Harry Craddock", sourceUrl: "",
    sourceRecipe: "Savoy Prohibition Punch (gin, lemon, grenadine, egg white)", recipeProvenance: "1930 Savoy punch.",
    historicalNotes: "Egg-white gin punch from the dry years—ironic naming as American Prohibition ended abroad.", rarity: "hidden_gem",
    funFact: "Craddock labeled this Prohibition Punch while London never went dry—the name sold newspapers.",
    yearInvented: 1930, regionOfOrigin: "London, UK", alternateNames: [],
    cocktail: cocktail({ name: "Prohibition Punch", slug: "prohibition-punch", glass: "Coupe", family: "Sour", method: "Shaken", tags: ["historical"], ingredients: [ing("london-dry-gin", "London dry gin", "spirit", 45), ing("lemon-juice", "Lemon juice", "juice", 22.5), ing("grenadine", "Grenadine", "syrup", 15), ing("egg-white", "Egg white", "dairy-egg", 1, "white")], garnish: ["Nutmeg"], preparation: ["Dry-shake, then shake with ice.", "Strain into a coupe.", "Grate nutmeg."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative", sourceTitle: "The Savoy Cocktail Book", sourceAuthor: "Harry Craddock", sourceUrl: "",
    sourceRecipe: "Savoy Violet Fizz (gin, crème de violette, lemon, egg white, soda)", recipeProvenance: "1930 Savoy fizz.",
    historicalNotes: "Crème de violette tints a gin fizz lavender—floral fizz family alongside the Aviation.", rarity: "hidden_gem",
    funFact: "Violet liqueur foams pink-purple under egg white—Craddock's floral answer to the Gin Fizz.",
    yearInvented: 1930, regionOfOrigin: "London, UK", alternateNames: [],
    cocktail: cocktail({ name: "Violet Fizz", slug: "violet-fizz", glass: "Collins", family: "Fizz", method: "Shaken", tags: ["historical"], ingredients: [ing("london-dry-gin", "London dry gin", "spirit", 45), ing("creme-de-violette", "Crème de violette", "liqueur", 15), ing("lemon-juice", "Lemon juice", "juice", 15), ing("simple-syrup", "Simple syrup", "syrup", 15), ing("egg-white", "Egg white", "dairy-egg", 1, "white"), ing("club-soda", "Club soda", "mixer", 60)], garnish: ["Lemon twist"], preparation: ["Dry-shake, shake with ice.", "Strain into Collins over ice.", "Top with soda."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative", sourceTitle: "The Savoy Cocktail Book", sourceAuthor: "Harry Craddock", sourceUrl: "",
    sourceRecipe: "Savoy Viking Fizz (aquavit, lemon, egg white, soda)", recipeProvenance: "1930 Savoy fizz.",
    historicalNotes: "Scandinavian spirit in a fizz template—caraway notes through citrus and foam.", rarity: "deep_cut",
    funFact: "Aquavit's caraway in a fizz reads like rye bread meets lemon meringue—Craddock's Nordic nod.",
    yearInvented: 1930, regionOfOrigin: "Scandinavia", alternateNames: [],
    cocktail: cocktail({ name: "Viking Fizz", slug: "viking-fizz", glass: "Collins", family: "Fizz", method: "Shaken", tags: ["historical"], ingredients: [ing("aquavit", "Aquavit", "spirit", 45), ing("lemon-juice", "Lemon juice", "juice", 15), ing("simple-syrup", "Simple syrup", "syrup", 15), ing("egg-white", "Egg white", "dairy-egg", 1, "white"), ing("club-soda", "Club soda", "mixer", 60)], garnish: ["Lemon wheel"], preparation: ["Dry-shake, shake with ice.", "Strain into Collins.", "Top with soda."] }),
  }),
  candidate({
    sourceTier: "other_verified", sourceTitle: "Spanish sangria tradition", sourceAuthor: "Regional house format", sourceUrl: "",
    sourceRecipe: "White sangria (white wine, brandy, citrus, soda)", recipeProvenance: "Documented Spanish punch service.",
    historicalNotes: "White wine sangria with brandy and seasonal fruit—lighter cousin to red sangria already in canon.", rarity: "well_known",
    funFact: "White sangria trades tannin for acidity—brandy and orange still anchor the punch bowl.",
    yearInvented: null, regionOfOrigin: "Spain", alternateNames: ["Sangria blanca"],
    cocktail: cocktail({ name: "White Sangria", slug: "white-sangria", glass: "Wine glass", family: "Punch", method: "Built", tags: ["classic"], ingredients: [ing("dry-white-wine", "Dry white wine", "wine", 120), ing("brandy", "Brandy", "spirit", 30), ing("orange-juice", "Orange juice", "juice", 30), ing("simple-syrup", "Simple syrup", "syrup", 15), ing("club-soda", "Club soda", "mixer", 30)], garnish: ["Orange slices", "apple"], preparation: ["Build in a pitcher with fruit.", "Chill and serve over ice.", "Top individual glasses with soda."] }),
  }),
  candidate({
    sourceTier: "high_quality_secondary", sourceTitle: "Beachbum Berry Remixed", sourceAuthor: "Jeff Berry", sourceUrl: "",
    sourceRecipe: "Polynesian Paralysis (multi-rum, gin, lime, orgeat)", recipeProvenance: "Berry tiki reconstruction.",
    historicalNotes: "Rum and gin share a tiki mug—orgeat and lime tie the spirits together in 1960s Polynesian pop style.", rarity: "deep_cut",
    funFact: "Gin in a tiki mug sounds wrong until orgeat and three rums show up—Polynesian Paralysis lives up to its name.",
    yearInvented: 1960, regionOfOrigin: "United States", alternateNames: [],
    cocktail: cocktail({ name: "Polynesian Paralysis", slug: "polynesian-paralysis", glass: "Tiki mug", family: "Tiki", method: "Blend", tags: ["tiki"], ingredients: [ing("rum-white", "White rum", "spirit", 30), ing("rum-dark", "Dark rum", "spirit", 30), ing("london-dry-gin", "London dry gin", "spirit", 22.5), ing("lime-juice", "Lime juice", "juice", 22.5), ing("orgeat", "Orgeat", "syrup", 15), ing("falernum", "Falernum", "liqueur", 7.5)], garnish: ["Mint sprig"], preparation: ["Blend with crushed ice.", "Pour into a tiki mug.", "Garnish with mint."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative", sourceTitle: "The Savoy Cocktail Book", sourceAuthor: "Harry Craddock", sourceUrl: "",
    sourceRecipe: "Savoy Apple Car (applejack, lemon, grenadine)", recipeProvenance: "1930 Savoy sour.",
    historicalNotes: "Applejack sour with grenadine—American apple spirit in a British bar book.", rarity: "deep_cut",
    funFact: "Applejack and grenadine make a pink sour without gin—Craddock filed it under whimsical fruit names.",
    yearInvented: 1930, regionOfOrigin: "United States", alternateNames: [],
    cocktail: cocktail({ name: "Apple Car", slug: "apple-car", glass: "Coupe", family: "Sour", method: "Shaken", tags: ["historical"], ingredients: [ing("applejack", "Applejack", "spirit", 45), ing("lemon-juice", "Lemon juice", "juice", 22.5), ing("grenadine", "Grenadine", "syrup", 15)], garnish: ["Lemon twist"], preparation: ["Shake with ice.", "Strain into a chilled coupe.", "Garnish with lemon twist."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative", sourceTitle: "The Savoy Cocktail Book", sourceAuthor: "Harry Craddock", sourceUrl: "",
    sourceRecipe: "Savoy Autumn Leaves (rye, vermouth, apricot, bitters)", recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "Seasonal rye and vermouth with apricot brandy—Craddock's autumnal Manhattan variant.", rarity: "deep_cut",
    funFact: "Apricot brandy in a rye Manhattan reads like fall orchard—Craddock named it for foliage, not fashion.",
    yearInvented: 1930, regionOfOrigin: "London, UK", alternateNames: [],
    cocktail: cocktail({ name: "Autumn Leaves", slug: "autumn-leaves", glass: "Coupe", family: "Manhattan", method: "Stirred", tags: ["historical"], ingredients: [ing("rye-whiskey", "Rye whiskey", "spirit", 45), ing("sweet-vermouth", "Sweet vermouth", "wine", 22.5), ing("apricot-brandy", "Apricot brandy", "liqueur", 15), ing("angostura-bitters", "Angostura bitters", "bitters", 2, "dash")], garnish: ["Orange twist"], preparation: ["Stir with ice.", "Strain into a chilled coupe.", "Garnish with orange twist."] }),
  }),
  candidate({
    sourceTier: "high_quality_secondary", sourceTitle: "Beachbum Berry Remixed", sourceAuthor: "Jeff Berry", sourceUrl: "",
    sourceRecipe: "Beachcomber (rum, triple sec, lime, Pernod substitute absinthe)", recipeProvenance: "1937 Donn Beach spec via Berry.",
    historicalNotes: "Don the Beachcomber's early rum sour with anise—precursor DNA to later tiki complexity.", rarity: "deep_cut",
    funFact: "The Beachcomber is Donn Beach before the mugs got monstrous—rum, curaçao, lime, and a whisper of anise.",
    yearInvented: 1937, regionOfOrigin: "Hollywood, USA", alternateNames: [],
    cocktail: cocktail({ name: "Beachcomber", slug: "beachcomber", glass: "Coupe", family: "Tiki", method: "Shaken", tags: ["tiki", "historical"], ingredients: [ing("rum-white", "White rum", "spirit", 45), ing("triple-sec", "Triple sec", "liqueur", 15), ing("lime-juice", "Lime juice", "juice", 22.5), ing("absinthe", "Absinthe", "spirit", 1, "dash")], garnish: ["Lime wheel"], preparation: ["Shake with ice.", "Strain into a chilled coupe.", "Garnish with lime."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative", sourceTitle: "The Savoy Cocktail Book", sourceAuthor: "Harry Craddock", sourceUrl: "",
    sourceRecipe: "Savoy Blackthorn (sloe gin, dry vermouth)", recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "Sloe gin and dry vermouth stirred—English hedgerow fruit in a low-ABV aperitif.", rarity: "hidden_gem",
    funFact: "Sloe gin's plum tartness against dry vermouth drinks like a British countryside aperitivo.",
    yearInvented: 1930, regionOfOrigin: "United Kingdom", alternateNames: [],
    cocktail: cocktail({ name: "Blackthorn", slug: "blackthorn", glass: "Coupe", family: "Aperitif", method: "Stirred", tags: ["classic"], ingredients: [ing("sloe-gin", "Sloe gin", "spirit", 45), ing("dry-vermouth", "Dry vermouth", "wine", 45), ing("angostura-bitters", "Angostura bitters", "bitters", 1, "dash")], garnish: ["Lemon twist"], preparation: ["Stir with ice.", "Strain into a chilled coupe.", "Garnish with lemon twist."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative", sourceTitle: "The Savoy Cocktail Book", sourceAuthor: "Harry Craddock", sourceUrl: "",
    sourceRecipe: "Savoy Charlie Chaplin (sloe gin, apricot, lime)", recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "Named for the silent-film star—sloe gin and apricot liqueur with lime in a balanced sour.", rarity: "hidden_gem",
    funFact: "Craddock named this for Chaplin while the actor was London's biggest draw—sloe gin gives the sour a plum spine.",
    yearInvented: 1930, regionOfOrigin: "London, UK", alternateNames: [],
    cocktail: cocktail({ name: "Charlie Chaplin", slug: "charlie-chaplin", glass: "Coupe", family: "Sour", method: "Shaken", tags: ["historical"], ingredients: [ing("sloe-gin", "Sloe gin", "spirit", 30), ing("apricot-liqueur", "Apricot liqueur", "liqueur", 30), ing("lime-juice", "Lime juice", "juice", 15)], garnish: ["Lime wheel"], preparation: ["Shake with ice.", "Strain into a chilled coupe.", "Garnish with lime."] }),
  }),
  candidate({
    sourceTier: "high_quality_secondary", sourceTitle: "Beachbum Berry Remixed", sourceAuthor: "Jeff Berry", sourceUrl: "",
    sourceRecipe: "Don the Beachcomber (1937 house blend)", recipeProvenance: "Berry reconstruction of early Donn spec.",
    historicalNotes: "Separate from dons-beachcomber in expanded set—this slug marks the classic named house cocktail format.", rarity: "deep_cut",
    funFact: "Berry distinguishes Don the Beachcomber the drink from Don the Beachcomber the bar—same owner, different recipe log.",
    yearInvented: 1937, regionOfOrigin: "Hollywood, USA", creator: "Donn Beach", alternateNames: [],
    cocktail: cocktail({ name: "Don the Beachcomber", slug: "don-the-beachcomber", glass: "Tiki mug", family: "Tiki", method: "Blend", tags: ["tiki", "historical"], ingredients: [ing("gold-rum", "Gold rum", "spirit", 45), ing("rum-dark", "Dark rum", "spirit", 22.5), ing("lime-juice", "Lime juice", "juice", 22.5), ing("grapefruit-juice", "Grapefruit juice", "juice", 22.5), ing("grenadine", "Grenadine", "syrup", 7.5), ing("falernum", "Falernum", "liqueur", 7.5)], garnish: ["Mint sprig"], preparation: ["Blend with crushed ice.", "Pour into a tiki mug.", "Garnish with mint."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative", sourceTitle: "The Savoy Cocktail Book", sourceAuthor: "Harry Craddock", sourceUrl: "",
    sourceRecipe: "Savoy Hawaiian Eye (rum, gin, vermouth, citrus)", recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "Split-spirit sour with vermouth—tiki-era naming before rum took over Hawaiian-themed drinks.", rarity: "deep_cut",
    funFact: "Gin and rum in one glass was Craddock's idea of exotic—vermouth keeps the Hawaiian Eye from becoming chaos.",
    yearInvented: 1930, regionOfOrigin: "United States", alternateNames: [],
    cocktail: cocktail({ name: "Hawaiian Eye", slug: "hawaiian-eye", glass: "Coupe", family: "Sour", method: "Shaken", tags: ["historical"], ingredients: [ing("rum-white", "White rum", "spirit", 30), ing("london-dry-gin", "London dry gin", "spirit", 30), ing("dry-vermouth", "Dry vermouth", "wine", 15), ing("lemon-juice", "Lemon juice", "juice", 15), ing("simple-syrup", "Simple syrup", "syrup", 7.5)], garnish: ["Lemon twist"], preparation: ["Shake with ice.", "Strain into a chilled coupe.", "Garnish with lemon twist."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative", sourceTitle: "The Savoy Cocktail Book", sourceAuthor: "Harry Craddock", sourceUrl: "",
    sourceRecipe: "Savoy Torpedo (gin, sweet vermouth, absinthe, bitters)", recipeProvenance: "1930 Savoy stirred spec.",
    historicalNotes: "Sweet vermouth-heavy gin stir with absinthe—naval naming in Craddock's metaphor-heavy index.", rarity: "deep_cut",
    funFact: "Craddock's Torpedo loads absinthe into a sweet vermouth Martini—one of the Savoy's more aggressive stirs.",
    yearInvented: 1930, regionOfOrigin: "London, UK", alternateNames: [],
    cocktail: cocktail({ name: "Torpedo", slug: "torpedo", glass: "Coupe", family: "Manhattan", method: "Stirred", tags: ["historical"], ingredients: [ing("london-dry-gin", "London dry gin", "spirit", 30), ing("sweet-vermouth", "Sweet vermouth", "wine", 45), ing("absinthe", "Absinthe", "spirit", 7.5), ing("angostura-bitters", "Angostura bitters", "bitters", 2, "dash")], garnish: ["Lemon twist"], preparation: ["Stir with ice.", "Strain into a chilled coupe.", "Garnish with lemon twist."] }),
  }),
];
