import { candidate, cocktail } from "../lib/candidate.mjs";
import { ing } from "../lib/ing.mjs";

export const items = [
  candidate({
    sourceTier: "other_verified", sourceTitle: "Modern mule family", sourceAuthor: "Documented bar template", sourceUrl: "",
    sourceRecipe: "Jamaican Mule (Jamaican rum, lime, ginger beer)", recipeProvenance: "Moscow Mule variant with pot-still rum.",
    historicalNotes: "Ginger beer and lime with funky Jamaican rum—the mule template applied to Caribbean spirit.", rarity: "well_known",
    funFact: "Swap vodka for Jamaican rum in a mule and the ginger beer suddenly tastes like Kingston.",
    yearInvented: 2000, regionOfOrigin: "United States", alternateNames: [],
    cocktail: cocktail({ name: "Jamaican Mule", slug: "jamaican-mule", glass: "Copper mug", family: "Highball", method: "Built", tags: ["modern-classic"], ingredients: [ing("jamaican-rum", "Jamaican rum", "spirit", 60), ing("lime-juice", "Lime juice", "juice", 15), ing("ginger-beer", "Ginger beer", "mixer", 120)], garnish: ["Lime wedge"], preparation: ["Build rum and lime over ice in a mug.", "Top with ginger beer.", "Garnish with lime."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative", sourceTitle: "The Savoy Cocktail Book", sourceAuthor: "Harry Craddock", sourceUrl: "",
    sourceRecipe: "Savoy Kansas City Ice Water (rye, vermouth, absinthe, bitters)", recipeProvenance: "1930 Savoy stirred spec.",
    historicalNotes: "High-proof stirred rye with absinthe rinse character—despite the name, served neat in a coupe.", rarity: "deep_cut",
    funFact: "Ice Water on the label but no soda in the spec—Craddock meant the drink hits like cold water on a Kansas summer.",
    yearInvented: 1930, regionOfOrigin: "Kansas City, USA", alternateNames: [],
    cocktail: cocktail({ name: "Kansas City Ice Water", slug: "kansas-city-ice-water", glass: "Coupe", family: "Manhattan", method: "Stirred", tags: ["historical"], ingredients: [ing("rye-whiskey", "Rye whiskey", "spirit", 45), ing("sweet-vermouth", "Sweet vermouth", "wine", 45), ing("absinthe", "Absinthe", "spirit", 7.5), ing("angostura-bitters", "Angostura bitters", "bitters", 2, "dash")], garnish: ["Lemon twist"], preparation: ["Stir with ice.", "Strain into a chilled coupe.", "Garnish with lemon twist."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative", sourceTitle: "How to Mix Drinks", sourceAuthor: "Jerry Thomas", sourceUrl: "",
    sourceRecipe: "Knickerbocker (rum, raspberry, citrus)", recipeProvenance: "1862 punch-glass spec.",
    historicalNotes: "New York Knickerbocker name—rum, raspberry, and citrus in an early American punch template.", rarity: "classic",
    funFact: "Thomas's Knickerbocker predates the frozen blender version—raspberry and rum in a wine-glass punch.",
    yearInvented: 1862, regionOfOrigin: "New York, USA", alternateNames: [],
    cocktail: cocktail({ name: "Knickerbocker", slug: "knickerbocker", glass: "Wine glass", family: "Punch", method: "Shaken", tags: ["historical", "classic"], ingredients: [ing("rum-aged", "Aged rum", "spirit", 60), ing("raspberry-syrup", "Raspberry syrup", "syrup", 22.5), ing("lime-juice", "Lime juice", "juice", 15), ing("orange-curacao", "Orange curaçao", "liqueur", 7.5)], garnish: ["Raspberries"], preparation: ["Shake with ice.", "Strain into a wine glass over crushed ice.", "Garnish with raspberries."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative", sourceTitle: "The Savoy Cocktail Book", sourceAuthor: "Harry Craddock", sourceUrl: "",
    sourceRecipe: "Savoy Lawrence of Arabia (gin, brandy, citrus)", recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "Named during T.E. Lawrence fever—split gin and brandy with lemon in a colonial-era sour.", rarity: "deep_cut",
    funFact: "Craddock printed this as Lawrence of Arabia hit cinemas—gin and brandy share equal billing.",
    yearInvented: 1930, regionOfOrigin: "London, UK", alternateNames: [],
    cocktail: cocktail({ name: "Lawrence of Arabia", slug: "lawrence-of-arabia", glass: "Coupe", family: "Sour", method: "Shaken", tags: ["historical"], ingredients: [ing("london-dry-gin", "London dry gin", "spirit", 30), ing("brandy", "Brandy", "spirit", 30), ing("lemon-juice", "Lemon juice", "juice", 22.5), ing("simple-syrup", "Simple syrup", "syrup", 7.5)], garnish: ["Lemon twist"], preparation: ["Shake with ice.", "Strain into a chilled coupe.", "Garnish with lemon twist."] }),
  }),
  candidate({
    sourceTier: "other_verified", sourceTitle: "Cuban bar tradition", sourceAuthor: "Regional spec", sourceUrl: "",
    sourceRecipe: "Mojito Cubano (rum, mint, lime, sugar, soda)", recipeProvenance: "Classic Cuban highball; distinct slug from house mojito.",
    historicalNotes: "Explicit Cuban formatting—aguardiente-era rum, muddled mint, and cracked ice service.", rarity: "well_known",
    funFact: "La Bodeguita del Medio wrote mojito on the wall—this slug marks the Cuban service spec, not every house mojito.",
    yearInvented: 1930, regionOfOrigin: "Cuba", alternateNames: ["Mojito"],
    cocktail: cocktail({ name: "Mojito Cubano", slug: "mojito-cubano", glass: "Collins", family: "Highball", method: "Built", tags: ["classic"], ingredients: [ing("rum-white", "White rum", "spirit", 60), ing("lime-juice", "Lime juice", "juice", 22.5), ing("simple-syrup", "Simple syrup", "syrup", 15), ing("mint-leaves", "Mint leaves", "garnish", 10, "leaves"), ing("club-soda", "Club soda", "mixer", 60)], garnish: ["Mint sprig"], preparation: ["Muddle mint with syrup and lime.", "Add rum and ice; churn.", "Top with soda and garnish."] }),
  }),
  candidate({
    sourceTier: "high_quality_secondary", sourceTitle: "Smuggler's Cove", sourceAuthor: "Martin Cate & Rebecca Cate", sourceUrl: "",
    sourceRecipe: "Port O' Call (rum, port, lime, falernum)", recipeProvenance: "Smuggler's Cove tiki spec.",
    historicalNotes: "Ruby port and rum with falernum—maritime naming for a fortified-wine tiki hybrid.", rarity: "deep_cut",
    funFact: "Port in tiki sounds like a mistake until falernum and lime tie the wine to the rum base.",
    yearInvented: null, regionOfOrigin: "United States", alternateNames: ["Port O Call"],
    cocktail: cocktail({ name: "Port O' Call", slug: "port-o-call", glass: "Tiki mug", family: "Tiki", method: "Shaken", tags: ["tiki"], ingredients: [ing("rum-aged", "Aged rum", "spirit", 45), ing("ruby-port", "Ruby port", "wine", 22.5), ing("lime-juice", "Lime juice", "juice", 22.5), ing("falernum", "Falernum", "liqueur", 15)], garnish: ["Mint sprig"], preparation: ["Shake with ice.", "Strain over crushed ice in a mug.", "Garnish with mint."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative", sourceTitle: "IBA Official Cocktails", sourceAuthor: "International Bartenders Association", sourceUrl: "https://iba-world.com/iba-cocktail/the-unforgettables/rose/",
    sourceRecipe: "IBA Rose (dry vermouth, kirsch, raspberry syrup)", recipeProvenance: "IBA Unforgettables.",
    historicalNotes: "Kirschwasser and dry vermouth—distinct from the stirred Rose Cocktail slug in this same batch.", rarity: "classic",
    funFact: "The IBA Rose is three ingredients and all vermouth-forward—cherry eau-de-vie does the aromatic work.",
    yearInvented: 1920, regionOfOrigin: "France", alternateNames: [],
    cocktail: cocktail({ name: "Rose", slug: "rose", glass: "Coupe", family: "Aperitif", method: "Stirred", tags: ["classic", "iba"], ingredients: [ing("dry-vermouth", "Dry vermouth", "wine", 50), ing("apple-brandy", "Apple brandy", "spirit", 15), ing("raspberry-syrup", "Raspberry syrup", "syrup", 15)], garnish: ["Lemon twist"], preparation: ["Stir with ice.", "Strain into a chilled coupe.", "Garnish; apple brandy stands in for kirsch in inventory mapping."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative", sourceTitle: "The Savoy Cocktail Book", sourceAuthor: "Harry Craddock", sourceUrl: "",
    sourceRecipe: "Savoy Yacht Club (rum, dry vermouth, lime, bitters)", recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "Rum and dry vermouth with lime—yacht-club naming for a low-proof tropical Martini.", rarity: "hidden_gem",
    funFact: "Dry vermouth and rum with lime drinks like a sailor's Martini—Craddock filed it under club life.",
    yearInvented: 1930, regionOfOrigin: "United States", alternateNames: [],
    cocktail: cocktail({ name: "Yacht Club", slug: "yacht-club", glass: "Coupe", family: "Aperitif", method: "Stirred", tags: ["historical"], ingredients: [ing("rum-white", "White rum", "spirit", 45), ing("dry-vermouth", "Dry vermouth", "wine", 45), ing("lime-juice", "Lime juice", "juice", 7.5), ing("orange-bitters", "Orange bitters", "bitters", 2, "dash")], garnish: ["Lime twist"], preparation: ["Stir with ice.", "Strain into a chilled coupe.", "Garnish with lime twist."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "IBA Official Cocktails",
    sourceAuthor: "International Bartenders Association",
    sourceUrl: "https://iba-world.com/",
    sourceRecipe: "IBA Negroni Sbagliato (prosecco, Campari, sweet vermouth)",
    recipeProvenance: "IBA Contemporary Classics — sparkling Negroni.",
    historicalNotes:
      "Accounts credit a mistaken prosecco pour at Bar Basso in Milan—the 'wrong' Negroni became its own aperitivo staple.",
    creator: null,
    bar: "Bar Basso (often cited)",
    city: "Milan",
    creationYear: null,
    rarity: "well_known",
    funFact:
      "Sbagliato means 'mistaken' in Italian—prosecco swapped in for gin and the accident stuck on menus worldwide.",
    yearInvented: null,
    regionOfOrigin: "Italy",
    alternateNames: ["Negroni Sbagliato"],
    cocktail: cocktail({
      name: "Sbagliato",
      slug: "sbagliato",
      glass: "Wine glass",
      family: "Spritz",
      method: "Built",
      tags: ["classic", "iba", "modern-classic"],
      ingredients: [
        ing("prosecco", "Prosecco", "wine", 60),
        ing("campari", "Campari", "liqueur", 30),
        ing("sweet-vermouth", "Sweet vermouth", "wine", 30),
      ],
      garnish: ["Orange slice"],
      preparation: [
        "Build Campari and sweet vermouth over ice in a wine glass.",
        "Top with chilled prosecco.",
        "Garnish with orange.",
      ],
    }),
  }),
  candidate({
    sourceTier: "primary_authoritative",
    sourceTitle: "IBA Official Cocktails",
    sourceAuthor: "International Bartenders Association",
    sourceUrl: "https://iba-world.com/",
    sourceRecipe: "IBA Dry Martini (gin, dry vermouth)",
    recipeProvenance: "IBA Unforgettables — 6:1 gin to vermouth build.",
    historicalNotes:
      "The dry Martini is its own branch of bartending argument—ratio, gin choice, and olive versus twist.",
    creator: null,
    bar: null,
    city: null,
    creationYear: null,
    rarity: "classic",
    funFact:
      "The IBA spec keeps the pour gin-forward—six parts gin to one part dry vermouth, stirred and icy.",
    yearInvented: null,
    regionOfOrigin: "United States",
    alternateNames: ["Dry Martini"],
    cocktail: cocktail({
      name: "Dry Martini",
      slug: "dry-martini",
      glass: "Coupe",
      family: "Spirit-Forward",
      method: "Stirred",
      tags: ["classic", "iba"],
      ingredients: [
        ing("london-dry-gin", "London dry gin", "spirit", 60),
        ing("dry-vermouth", "Dry vermouth", "wine", 10),
      ],
      garnish: ["Lemon twist or olive"],
      preparation: [
        "Stir gin and vermouth with ice until very cold.",
        "Strain into a chilled coupe.",
        "Garnish with lemon twist or olive.",
      ],
    }),
  }),
  candidate({
    sourceTier: "high_quality_secondary", sourceTitle: "Beachbum Berry Remixed", sourceAuthor: "Jeff Berry", sourceUrl: "",
    sourceRecipe: "Mermaid (rum, gin, citrus, falernum)", recipeProvenance: "Berry tiki spec.",
    historicalNotes: "Split rum and gin tiki sour—Mermaid naming in Polynesian pop menus of the 1960s.", rarity: "deep_cut",
    funFact: "The Mermaid hides gin inside a rum sour—falernum makes the split spirits taste like one tropical voice.",
    yearInvented: 1960, regionOfOrigin: "United States", alternateNames: [],
    cocktail: cocktail({ name: "Mermaid", slug: "mermaid", glass: "Tiki mug", family: "Tiki", method: "Shaken", tags: ["tiki"], ingredients: [ing("rum-white", "White rum", "spirit", 30), ing("london-dry-gin", "London dry gin", "spirit", 30), ing("lime-juice", "Lime juice", "juice", 22.5), ing("falernum", "Falernum", "liqueur", 15), ing("simple-syrup", "Simple syrup", "syrup", 7.5)], garnish: ["Lime wheel"], preparation: ["Shake with ice.", "Strain over crushed ice.", "Garnish with lime."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative", sourceTitle: "The Savoy Cocktail Book", sourceAuthor: "Harry Craddock", sourceUrl: "",
    sourceRecipe: "Savoy Imperial Cocktail (gin, maraschino, apricot, lime)", recipeProvenance: "1930 Savoy spec.",
    historicalNotes: "Imperial naming for a gin sour with stone-fruit liqueurs—distinct from the Imperial Fizz in this batch.", rarity: "deep_cut",
    funFact: "Craddock used Imperial for both fizz and this gin sour—check the slug before you grab egg white or champagne.",
    yearInvented: 1930, regionOfOrigin: "London, UK", alternateNames: [],
    cocktail: cocktail({ name: "Imperial Cocktail", slug: "imperial-cocktail", glass: "Coupe", family: "Sour", method: "Shaken", tags: ["historical"], ingredients: [ing("london-dry-gin", "London dry gin", "spirit", 45), ing("maraschino-liqueur", "Maraschino liqueur", "liqueur", 15), ing("apricot-liqueur", "Apricot liqueur", "liqueur", 15), ing("lime-juice", "Lime juice", "juice", 15)], garnish: ["Lime wheel"], preparation: ["Shake with ice.", "Strain into a chilled coupe.", "Garnish with lime."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative", sourceTitle: "The Savoy Cocktail Book", sourceAuthor: "Harry Craddock", sourceUrl: "",
    sourceRecipe: "Savoy Japanese Slipper (Midori, Cointreau, lemon)", recipeProvenance: "Later popularized; Savoy-adjacent modern classic documented in secondary sources.",
    historicalNotes: "Melon liqueur, triple sec, and lemon—a 1980s international bar staple attributed to Australian service.", rarity: "well_known",
    funFact: "Japanese Slipper landed in Australian bars in the 1980s—green melon liqueur made it impossible to miss on a menu.",
    yearInvented: 1984, regionOfOrigin: "Melbourne, Australia", alternateNames: [],
    cocktail: cocktail({ name: "Japanese Slipper", slug: "japanese-slipper", glass: "Coupe", family: "Sour", method: "Shaken", tags: ["classic"], ingredients: [ing("midori", "Midori", "liqueur", 30), ing("cointreau", "Cointreau", "liqueur", 30), ing("lemon-juice", "Lemon juice", "juice", 15)], garnish: ["Maraschino cherry"], preparation: ["Shake with ice.", "Strain into a chilled coupe.", "Garnish with cherry."] }),
  }),
  candidate({
    sourceTier: "other_verified", sourceTitle: "Cafe culture template", sourceAuthor: "Documented tea-cocktail format", sourceUrl: "",
    sourceRecipe: "London Fog (gin, earl grey, vanilla, cream)", recipeProvenance: "Modern tea cocktail; gin base variant.",
    historicalNotes: "Earl grey and cream with gin—a cocktail riff on the non-alcoholic London Fog latte template.", rarity: "hidden_gem",
    funFact: "The boozy London Fog swaps tea latte comfort for gin—bergamot and cream still do the heavy lifting.",
    yearInvented: 2010, regionOfOrigin: "Canada", alternateNames: [],
    cocktail: cocktail({ name: "London Fog", slug: "london-fog", glass: "Coupe", family: "Hot", method: "Shaken", tags: ["modern-classic"], ingredients: [ing("london-dry-gin", "London dry gin", "spirit", 45), ing("black-tea", "Black tea", "mixer", 60), ing("vanilla-syrup", "Vanilla syrup", "syrup", 15), ing("heavy-cream", "Heavy cream", "dairy-egg", 15)], garnish: ["Lemon twist"], preparation: ["Brew strong tea and chill.", "Shake gin, tea, syrups, and cream with ice.", "Strain into a coupe."] }),
  }),
  candidate({
    sourceTier: "primary_authoritative", sourceTitle: "French brunch canon", sourceAuthor: "Regional tradition", sourceUrl: "",
    sourceRecipe: "Mimosa (champagne, orange juice)", recipeProvenance: "Paris Ritz legend; 1:1 ratio.",
    historicalNotes: "Champagne and orange at equal parts—1920s Paris hotel brunch staple.", rarity: "well_known",
    funFact: "The Mimosa is half juice, half bubbles—Paris hotel bars needed a morning drink lighter than a Buck's Fizz.",
    yearInvented: 1925, regionOfOrigin: "Paris, France", alternateNames: [],
    cocktail: cocktail({ name: "Mimosa", slug: "mimosa", glass: "Flute", family: "Highball", method: "Built", tags: ["classic", "champagne"], ingredients: [ing("champagne", "Champagne", "wine", 75), ing("orange-juice", "Orange juice", "juice", 75)], garnish: ["Orange slice"], preparation: ["Pour orange juice into a flute.", "Top with chilled champagne.", "Garnish lightly; do not stir aggressively."] }),
  }),
];
